### ISSUE TITLE
Copying qtlogging.ini doesn't actually work as expected

### ISSUE THREAD

**Issue by bhush9** [postmarketOS/pmbootstrap#1038]
If I understand correctly, user is added *before* the packages are installed, resulting in this never getting copied in user home.. (I can not confirm this, but this issue is created based on reading pmb log).

https://github.com/postmarketOS/pmbootstrap/blob/917f03d5f9f015fa9fc0be8093d87b7f21d98d4a/aports/main/postmarketos-ui-plasma-mobile/APKBUILD#L27

**Comment by ollieparanoid** [comment]
Just tested with the following results on my `samsung-i9100`:

* `/etc/skel/.config/QtProject/qtlogging.ini` exists in the resulting rootfs chroot after installation
* it exists in the system image/sd card
* the system image/sd card has it copied in the home folder - SSH output from the device:
```
localhost:~/.config/QtProject$ ls -lah
total 12
drwxr-xr-x    2 user     root        4.0K Dec 29  2017 .
drwxr-xr-x    3 user     root        4.0K Dec 29  2017 ..
-rw-r--r--    1 user     root        2.0K Dec 23  2017 qtlogging.ini
```
* I've saved the output of `logread` with the `qtlogging.ini` file and without it (just moved `.config` to `_config`). There's more QT logging output with the `qtlogging.ini` file, so I'm sure it works.
Example: `kwin_libinput: Libinput:` is only present when `qtlogging.ini` is there.

My conclusion is, that it works 👍 If you had a report that it was not working before, it was probably because there was no new installation performed (which creates a new user), but only the `postmarketos-ui-plasma-mobile` package was upgraded.

Please reply if someone is not having the file after a fresh install!

**Comment by ollieparanoid** [comment]
@asiekierka reported in #1088 that he did not have the `qtlogging.ini` file.

Would it be possible, that you attach your entire `~/.local/var/pmbootstrap/log.txt` file here as file attachment?

Alternatively, if you are able to reproduce this, the `pmbootstrap log` of one full `pmbootsrap install` run (the chroots need to be delete beforehand with `pmbootstrap zap`) would be even better.

Thanks!

**Comment by asiekierka** [comment]
@ollieparanoid I had it in /etc/skel, but not in /home/user.

More info and reproduction is necessary - due to #1091 I had to install postmarketOS using an unsupported method (manually following the recovery ZIP installer script's instructions).

**Comment by ollieparanoid** [comment]
Could you check if the config file is present in `pmbootstrap chroot -r`? That's the rootfs chroot, from which the (android recovery zip) image gets created.

**Comment by ollieparanoid** [comment]
We have the following function, which creates the home folder as copy from `/etc/skel` after all packages have been installed:

https://github.com/postmarketOS/pmbootstrap/blob/fd67263c2737e26e8eed40536211b8db32f6e90e/pmb/install/install.py#L94-L107

But this function only gets called when creating the image file. I have checked the android recovery zip code, and it seems like it does not create the `/home/$user` folder (at all? CC: @ata2001).

So my guess is that @asiekierka and @MoreRobustThanYou (you were missing the `qtlogging.ini` too, right?) were both using the Android recovery install zip method. Is that correct?

I think we can solve it with something like the following (untested):

```diff
--- a/aports/main/postmarketos-android-recovery-installer/pmos_install
+++ b/aports/main/postmarketos-android-recovery-installer/pmos_install
@@ -98,6 +98,11 @@ mount -t ext2 -rw "$PMOS_BOOT" /mnt/pmOS/boot || {
 }
 ui_print "Installing rootfs..."
 unzip -p pmos.zip rootfs.tar.gz | tar -xz -C /mnt/pmOS
+
+ui_print "Creating home folder..."
+user="$(cat /mnt/pmOS/etc/passwd | grep ":1000:" | cut -d ':' -f 1)"
+cp -a /mnt/pmOS/etc/skel /mnt/pmOS/home/"$user"
+chown -R 1000 /mnt/pmOS/home/"$user"
+
 if [ "$FLASH_KERNEL" = "true" ]
 then
        if [ "$ISOREC" = "true" ]
```

(NOTE: We need to create the user *before* installing the postmarketOS-packages, because it needs to be present so we can [enable autologin](https://github.com/postmarketOS/pmbootstrap/blob/fd67263c2737e26e8eed40536211b8db32f6e90e/aports/main/postmarketos-ui-weston/postmarketos-ui-weston.post-install) for it. The situation will be improved once we have a display manager #656.)
