### ISSUE TITLE
"BAD signature" & file missing APKINDEX.tar.gz while running pmbootstrap install

### ISSUE THREAD

**Issue by Nopey** [postmarketOS/pmbootstrap#1109]
I'm on Ubuntu 17.04 with kernel 4.10.0-42-generic (x86_64)
Log:
http://paste.ubuntu.com/26357244/

**Comment by ollieparanoid** [comment]
Welcome to postmarketOS and thanks for opening this issue!

> WARNING: Ignoring /mnt/pmbootstrap-packages/x86_64/APKINDEX.tar.gz: No such file or directory

`APKINDEX.tar.gz` is an index file for packages in a package repository. With `pmbootstrap` it is possible to locally compile your own packages, and after you compile the first package (e.g. with `pmbootstrap build hello-world --force` - force because then it does not use the version from the binary repo), the index in `/mnt/pmbootstrap-packages` will be generated.
So this warning is expected and not something critical.

> (1/2) Installing qemu-user-static-repack (2.8-r10)
> ERROR: Failed to create usr/bin/qemu-mips-static: No error information
> ERROR: qemu-user-static-repack-2.8-r10: BAD signature

Looks like the download of the `qemu-user-static-repack` package was aborted. Could you verify its file size with the size from the package from the repo?
```shell
ls -lah ~/.local/var/pmbootstrap/cache_apk_x86_64/qemu-user-static*
```

It should be `32 MB` in size (see <http://postmarketos.brixit.nl/x86_64/>, on my system it shows as 33 MB with `ls`). If your package is significantly smaller, just delete the file (with `sudo rm`). It should download the package again in that case.

As last resort, if the download won't work for whatever reason, you can simply build the package by yourself with `pmbootstrap build qemu-user-static-repack --force`. It will then use the local version.

**Comment by ollieparanoid** [comment]
Please let us know if this is not solved for you.

**Comment by Nopey** [comment]
I'm currently busy, will continue this sometime February. Thank you for the help. To prevent similar problems in the future, perhaps the script that downloads the files could cache the incomplete copies in `/tmp` and only save them once the download is complete?

**Comment by Nopey** [comment]
Yesterday I tried deleting the entire cache folder, and rerunning the program. This fixed it. Thanks for the help. To prevent similar problems in the future, perhaps the script that downloads the files could check if they are complete/correct (hashsum or temp download location could work)

**Comment by ollieparanoid** [comment]
These packages get downloaded by `apk` (Alpine package keeper, nothing to do with Android's app format). It verifies the signatures of these binaries, hence the "BAD signature" message and refuses to use them because of that (it could be a man in the middle attack after all).
