### ISSUE TITLE
gtk+2.0-maemo-2.24.31-r3.apk is rebuilt in each and every build

### ISSUE THREAD

**Issue by pavelmachek** [postmarketOS/pmbootstrap#1156]
Configure for nokia n900 with xfce4. Then, gtk+-maemo is rebuilt, in each and every build, and even two times doing one build?! It takes 40 minutes to build, so ... it is a bit of a problem. First build:

[12:51:31] (buildroot_armhf) build armhf/gtk+2.0-maemo-2.24.31-r3.apk
[13:28:49] (buildroot_armhf) install mesa-egl xfce4 xorg-server
[13:29:00] (buildroot_armhf) build armhf/postmarketos-ui-xfce4-0.1-r0.apk
[13:29:07] (buildroot_armhf) build armhf/gtk+2.0-maemo-2.24.31-r3.apk

(I'll post second build when this finishes).

I get these warnings, but they may not be related:

>>> gtk+2.0-maemo*: Script found. /bin/sh added as a dependency for gtk+2.0-maemo-2.24.31-r3.apk
/usr/bin/abuild: line 2554: git: not found

**Comment by ollieparanoid** [comment]
Related: #1023

This problem probably goes away when you disable timestamp based rebuilds, because it fails to detect which packages need to be rebuilt if the pkgrel and pkgver is the same.

* Do you have timestamp based rebuilds enabled (it's the default and can be changed in `pmbootstrap init`)? Check with: `pmbootstrap config timestamp_based_rebuild`

* Could you attach the log? It should list why it decides to build packages. There's (a lot!) more information with the `-v` flag (e.g. `pmbootstrap -v install`)

Thanks for reporting!

**Comment by pavelmachek** [comment]
pavel@duo:/data/l/pmos/pmbootstrap$ ./pmbootstrap.py config timestamp_based_rebuild
True
pavel@duo:/data/l/pmos/pmbootstrap$ 

So yes, timestamp-based-rebuilds seems to be the problem. Can you try to run the build with similar parameters?

**Comment by pavelmachek** [comment]
With -v, yes, I seem to get some additional information:

(014167) [23:22:24] (buildroot_armhf) % cd /home/pmos/build && busybox su pmos -c 'CCACHE_PATH=/usr/lib/arch-bin-masquerade/armhf:/usr/bin CCACHE_COMPILERCHECK=string:6.4.0-r6 CARCH=armhf CCACHE_PREFIX=distcc DISTCC_HOSTS=127.0.0.1:33632 abuild -d'
>>> gtk+2.0-maemo: abuild 3.1.0-r4
>>> gtk+2.0-maemo: Checking sanity of /home/pmos/build/APKBUILD...
>>> WARNING: gtk+2.0-maemo: You should not have $install in source
>>> WARNING: gtk+2.0-maemo: You should not have $install in source
>>> WARNING: gtk+2.0-maemo: You should not have $install in source
>>> WARNING: gtk+2.0-maemo: No maintainer
>>> gtk+2.0-maemo: Cleaning temporary build dirs...
>>> gtk+2.0-maemo: Fetching http://ftp.gnome.org/pub/gnome/sources/gtk+/2.24/gtk+-2.24.31.tar.xz

**Comment by ollieparanoid** [comment]
I would need your log to reproduce the problem. The timestamp based builds logic tries to detect which packages need to be rebuilt even if the version (pkgver, pkgrel) did not change.

This seems easy at first, but in combination with git, when you switch branches or just cloned a repo, then the files will have newer timestamps than the binary packages. So `pmbootstrap` would think they need to be rebuilt.

To work around this, we ask `git` to diff against current `master`, and only look at the files that have changed in regard to `master`. But this only seems to work correctly when using `git rebase` instead of `git merge` (and I'm not 100% sure of that even, need to investigate this more). This feature got even more complicated as the binary repo was introduced.

Could you attach the full log during one build (e.g. as attachment here in the comments)?

**Comment by pavelmachek** [comment]
I'm definitely using git merges... And I do have:

/usr/bin/abuild: line 2554: git: not found

in the logs. Is that failure expected / could it be related? And yes, turning off timestamp-based builds did the trick.

**Comment by ollieparanoid** [comment]
That is expected. In Alpine, the folder where `abuild` gets executed is a git repository. With pmbootstrap this is not the case, as we copy all files for one aport (APKBUILD, patches, ...) to the regular folder `$chroot`/home/pmos/build.
`abuild` tries to write down which git commit the aport had at compile time, that's why it executes git. And fails, because `git` is not installed in the native chroot, and even if it was, this would not be a git folder anyway.

This is not related to `pmbootstrap`'s git checking, which relies on the host system's git binary (if git should not be installed, this falls back gracefully).

So... do you want to share the log?

**Comment by pavelmachek** [comment]
Ok, let me try ./pmbootstrap.py -v install . I re-configured for
time-based rebuilds, and sure enough, it tries to build gtk+.

**Comment by pavelmachek** [comment]
[log.txt](https://github.com/postmarketOS/pmbootstrap/files/1667477/log.txt)

I stopped build when it started compiling gtk+. Let me know if you need full log.

**Comment by ollieparanoid** [comment]
Actually we've discussed in #1167 (as linked above) whether it would be better to remove this feature, as this is buggy right now (depending on how you use git, and with the binary repo enabled in general), and it's too hard to get it right if it is even possible. No one seems to be against removing it, so I will make a PR later that removes this feature altogether.

Thanks a lot for creating and posting the log though, I know that this takes some time and effort as well, and I appreciate it!
