### ISSUE TITLE
Can't connect to SSH 

### ISSUE THREAD

**Issue by Nutcake** [postmarketOS/pmbootstrap#116]
Currently trying to port for the LG G3, however after booting the kernel with 
` # pmbootstrap flasher boot ` 
and entering the decryption passphrase over telnet, the device closes the connection as expected but then does not seem to do anything. The display doesn't get updated and just shows the fastboot log (which could be related to #66 ?). The device is pingable but all ports are closed, so SSH obviously fails with "Connection refused".
The DEVTMPFS flag is set and I tried setting DEVTMPFS_AUTO as well, with no change.
How do I debug the system in this state without SSH access?

**Comment by ollieparanoid** [comment]
First of all, it's great news that you are working on a port, thanks a lot for that!

You could start with debugging by enabling the regular telnet shell in the initramfs, see the [end of the porting guide](https://github.com/postmarketOS/pmbootstrap/wiki/Porting-to-a-new-device) for more information.

Maybe that helps already to find out why it does not work - if it does not, try the following (untested!):
1. remove the "telnet" from the "killall" statement in [`init.sh.in`](https://github.com/postmarketOS/pmbootstrap/blob/master/aports/postmarketos-mkinitfs/init.sh.in#L32)
1. rebuild `postmarketos-mkinitfs`
1. reinstall the mkinitfs hook - the easiest way right now is to zap your chroot (there are better ways, but they need longer explanation as of now. I'm working on improving this.)
1. boot your custom kernel/initramfs again, which should now have the modified initramfs, and where it should not kill the telnet shell after it continues booting with OpenRC. I *assume* that you can then try to start sshd manuall from telnet, and see the error message.

(I have planned to extend the usb shell hook, that it always keeps the telnet session open, when enabled. but as I said, I am not sure if it will work that way.)

Last but not least, if you have access to a serial console somehow (you can build yourself a cable for some phones, that go into the audio jack and output serial), you can use that to read all boot messages.

(I recommend to turn off `DEVTMPFS_AUTO` again, because this only means, that `/dev` gets mounted automatically - OpenRC does that, it is not necessary.)

**Comment by Nutcake** [comment]
Alright, so with those changes connecting to the initramfs session with telnet over standard port 23 still results in the connection getting terminated after entering the passphrase, however when connecting to the shell on port 24 and running ./init from there (which is what I assume the telnet session on port 23 does when connecting?) I get a whole bunch of nice errors:
```
/ # ./init
modprobe: can't change directory to '/lib/modules': No such file or directory
mount: mounting proc on /proc failed: Resource busy
mount: mounting sysfs on /sys failed: Resource busy
mount subpartitions of /dev/mmcblk0p40
mount: mounting devpts on /dev/pts failed: Resource busy
---
WARNING: usb shell is active on 172.16.42.1:24.
This is a security hole! Only use it for debugging, and
uninstall the usb-shell hook afterwards!
---
Enter passphrase for /dev/mapper/mmcblk0p40p2: 
umount: can't unmount /dev/pts: Resource busy
umount: can't unmount /dev: Invalid argument
BusyBox v1.26.2 (2017-06-11 06:37:20 GMT) multi-call binary.

Usage: switch_root [-c /dev/console] NEW_ROOT NEW_INIT [ARGS]

Free initramfs and switch to another root fs:
chroot to NEW_ROOT, delete all in /, move NEW_ROOT to /,
execute NEW_INIT. PID must be 1. NEW_ROOT must be a mountpoint.

        -c DEV  Reopen stdio to DEV after switch
/ # 
```

**Comment by ollieparanoid** [comment]
Did you remove "telnet" from the "killall" line?

Well, the script already gets executed once, so a whole bunch of errors is expected, because it can not mount `/proc` again, as it is already mounted etc.

I guess the `switch_root` error [from here](https://github.com/postmarketOS/pmbootstrap/blob/master/aports/postmarketos-mkinitfs/init.sh.in#L38) is caused, because another instance of `init.sh` is already running, and that instance executed the `switch_root` already, so you can't switch it again, and `/sysroot` has already moved to `/`.

What happens, when you type `ls /` and `ps ax` after your described procedure? (Has the root file system changed to the "real" one in the encrypted partition, and is OpenRC running? If it is, you could try to start sshd now and see why it fails.)

**Comment by Nutcake** [comment]
Telnet is definitely removed from the killall line, as the change can be seen in the /init script in the initramfs.
Running /init from the shell does not seem to change the file system root, and also breaks the /proc mount, as the folder is empty afterwards, so ps ax prints nothing.
When connecting to the shell on 24 and removing telnetd from the killall line in /telnet_connect.sh, then connecting to port 23 in another shell and entering the passphrase, the second connection still gets closed, but the first connection to the shell remains, and shows that nothing has changed in the rootfs.

**Comment by ollieparanoid** [comment]
Okay, thanks for testing that.
What happens, when you connect via telnet, and run the following steps manually, one after another, could you post the output please?
```shell
source /init_functions.sh
export partition="$(find_root_partition)"
echo "root partition: $partition"
cryptsetup luksOpen "$partition" root
mount -w -t ext4 /dev/mapper/root /sysroot
umount /proc
umount /sys
umount /dev/pts
umount /dev
switch_root /sysroot /sbin/init
```

**Comment by Nutcake** [comment]
```
/ # source /init_functions.sh
/ # export partition="$(find_root_partition)"
/ # echo "root partition: $partition"
root partition: /dev/mapper/mmcblk0p40p2
/ # cryptsetup luksOpen "$partition" root
Enter passphrase for /dev/mapper/mmcblk0p40p2: 
/ # mount -w -t ext4 /dev/mapper/root /sysroot
/ # umount /proc
/ # umount /sys
/ # umount /dev/pts 
umount: can't unmount /dev/pts: Resource busy
/ # umount /dev
umount: can't unmount /dev: Invalid argument
/ # switch_root /sysroot /sbin/init
BusyBox v1.26.2 (2017-06-11 06:37:20 GMT) multi-call binary.

Usage: switch_root [-c /dev/console] NEW_ROOT NEW_INIT [ARGS]

Free initramfs and switch to another root fs:
chroot to NEW_ROOT, delete all in /, move NEW_ROOT to /,
execute NEW_INIT. PID must be 1. NEW_ROOT must be a mountpoint.

        -c DEV  Reopen stdio to DEV after switch
```

**Comment by ollieparanoid** [comment]
Okay, the `switch_root` does not work, because when logged in into telnet, you're not running as PID 1.
Let's see if the `/sysroot` partition was mounted right. Do this after manually mounting as shown above:
```shell
ls /sysroot
ls -lah /sysroot/sbin/init
```

Other than that I am out of ideas right now. But feel free to join the IRC (again), maybe we can brainstorm there. It's also faster than waiting for answers on GitHub issues.

**Comment by Nutcake** [comment]
```
/ # ls /sysroot
bin         dev         home        lost+found  mnt         root        sbin        sys         usr
boot        etc         lib         media       proc        run         srv         tmp         var
/ # ls -lah /sysroot/sbin/init 
lrwxrwxrwx    1 0        0             12 Jun 26  2017 /sysroot/sbin/init -> /bin/busybox
```
Joined the IRC now.

**Comment by Nutcake** [comment]
Somehow fixed itself after a troubleshooting session in IRC, not sure how or why. Maybe my chroots were in a weird state and zapping and rebuilding a few times fixed it.

**Comment by Nutcake** [comment]
I figured out what fixed it, however it doesn't make much sense to me.
Adding these two lines
```
exec > /initlog
exec 2>&1
```
to the beginning of `aports/postmarketos-mkinitfs/init.sh.in` and rebuilding that package fixes the problem. I initially did that so I would have a logfile I could look at but just adding those two lines makes the system boot successfully. Removing them again causes switch_root to fail again, so it's the modification that fixes it, not the process of zapping and rebuilding.
Any idea whats going on here?

**Comment by ollieparanoid** [comment]
What the hell!
I guess, it has problems with the stdout/stderr streams, but I do not understand why this causes `switch_root` to fail o_O
The `0.1.x` version of `postmarketos-mkinitfs` has logging enabled [by default](https://github.com/postmarketOS/pmbootstrap/blob/master/aports/postmarketos-mkinitfs/init_functions.sh#L19) (it can be turned off via kernel command line by specifying `PMOS_NO_OUTPUT_REDIRECT` there), so it should always work for you.
If you want to, you could try if the new version has the same problem, when you *turn off* the logging to a file. What is also new is, that after a failed switch_root, it loops forever, so you can debug this better with telnet (instead of getting a reboot).

**Comment by Nutcake** [comment]
The thing is, I was already using the new version that has the `PMOS_NO_OUTPUT_REDIRECT` flag and the `pmOS_init.log` file gets created correctly but it still fails without my modification. I haven't tried setting the flag yet, but I might do that next, just to see if it changes anything. Also, it might not be switch_root failing, but that just being a side effect of running /init twice for debugging. The log file doesn't contain any helpful information after entering the passphrase on port 23, so it looks like all commands run fine, but the switch just fails without error.
Anyway, I might debug this problem further in the future but since it works right now I want to focus on getting WiFi to run and figuring out why weston-terminal doesn't work correctly.
