### ISSUE TITLE
replace postmarketos-splash with plymouth

### ISSUE THREAD

**Issue by lramage94** [postmarketOS/pmbootstrap#1187]
Many Linux distributions use plymouth for bootsplash as it is written in C/C+ and integrates with the initramfs early on during the boot process.

homepage: https://www.freedesktop.org/wiki/Software/Plymouth/

**Comment by ollieparanoid** [comment]
Right now we use busybox' `fbsplash` to display the splash screens. All splash-screens are pre-generated images, so we don't need to do any font rendering. Since we need busybox in the initramfs anyway, that means we don't have any additional executable. We only need to add the pre-generated splash images to the initramfs, which are pretty small when compressed.

Plymouth seems to be quite heavy regarding [dependencies](https://pkgs.alpinelinux.org/package/edge/community/armhf/plymouth) (on the top right on that page):
* cairo
* evdev-libs
* glib
* libpng
* pango

So this would make the initramfs a lot bigger, which means that it couldn't be flashed to all devices anymore (we already had space problems and created `initramfs-extra` for that, where `osk-sdl` is in for example, but the splash screens need to be in the main `initramfs` so we can display an error on-screen when `initramfs-extra` fails to load).

Thanks for posting the idea!

**Comment by lramage94** [comment]
I see, so would it be possible to just rewrite postmarketos-splash in bash/ash/sh, or even c?

**Comment by ollieparanoid** [comment]
If you want to go for size, then rewriting it in C would be the best method. Keep in mind that it supports a ini-like config file right now, which one can use to adjust the splash screen (see the images in #206). 

While the python code is not the smallest and fastest, its advantages are that it is short and therefore easy to maintain. So if someone wants to work on that I would recommend to make sure that we don't lose the latter characteristics (e.g. by depending on a ready to use ini parser and font library instead of writing something from scratch).

**Comment by lramage94** [comment]
Well I will look into it and see what I can do.
