### ISSUE TITLE
After upgrading pkgrel, the package is not installed in the rootfs

### ISSUE THREAD

**Issue by PabloCastellano** [postmarketOS/pmbootstrap#120]
After a successful `pmboostrap install` I've done some changes in my aports/device-motorola-titan/profile.sh file, bumped pkgrel and updated the checksums.

When I run `pmbootstrap install` again, I can see that the newer version of device-motorola-titan package is built again but if I enter the chroot (--suffix=rootfs_motorola-titan) the file doesn't contain the latest changes. 

The last version that was compiled has not been installed!

Workaround: zap -p and install again

**Comment by ollieparanoid** [comment]
Quick workaround: `pmbootstrap chroot --suffix=rootfs_samsung-i9100`, `apk add /home/user/packages/user/armhf/your-package.apk`

But you are absolutely right, this should be fixed and I am working on that. Thanks for the report!

**Comment by PabloCastellano** [comment]
So what is the root of this problem? I have not investigated but is it simply that is not installed after being built?

**Comment by ollieparanoid** [comment]
In `pmbootstrap install`, the function `pmb.chroot.apk.upgrade` [gets called](https://github.com/postmarketOS/pmbootstrap/blob/5d62a36bb84c5590acf2d18022e158037d3df15a/pmb/install/install.py#L93), which is [supposed to take care](https://github.com/postmarketOS/pmbootstrap/blob/5d62a36bb84c5590acf2d18022e158037d3df15a/pmb/chroot/apk.py#L95) of upgrading all packages, that are out of date by wrapping `apk upgrade -a`.

That does not seem to work with self built packages for some reason? I am not sure, if this is a bug in `apk` or if `pmbootstrap` uses it wrong. Either way, it has been requested, that `pmbootstrap` also supports rebuilding packages without `--force`, when the `pkgrel` and `pkgver` did *not* change, but the APKBUILD or other files in the aport folder changed. So it is more intuitive, and more like `make` does it.

This feature is not supported by `apk`, and to get that working properly, `pmbootstrap` must detect out of date packages by itself instead of relying on `apk`.
