### ISSUE TITLE
install fails with libv4l package error

### ISSUE THREAD

**Issue by Alexandroid99** [postmarketOS/pmbootstrap#1300]
I'm trying to make a test build for the Nexus 9 and when I choose the Plasma-Mobile desktop I run into this error:

`[09:43:03] NOTE: Run 'pmbootstrap pkgrel_bump --auto' to mark packages with outdated dependencies for rebuild. This will most likely fix this issue (soname bump?).
[09:43:03] ERROR: Could not find package 'so:libv4l2.so.0' in any aports folder or APKINDEX.`

arch is aarch64

Selecting mate as the desktop avoids this issue but I really want plasma because of the chance of hw acceleration.

**Comment by z3ntu** [comment]
Did you try to run `pmbootstrap pkgrel_bump --auto`?

**Comment by Alexandroid99** [comment]
Several times as it's the suggested fix in the error message, duh. I did some digging and apparently stuff related to v4l fails to install complaining about world dependencies not being fulfilled (when chrooting), maybe that's related?

**Comment by PureTryOut** [comment]
I'm guessing the following commit in the Alpine Linux aports repository has something to do with this. https://github.com/alpinelinux/aports/commit/689327e79503480e774cff04560f8e4c695f5824

**Comment by ollieparanoid** [comment]
Thanks for reporting!
The `pmbootstrap pkgrel_bump --auto` only helps, when the package that has broken dependencies is in postmarketOS' aports.

But as @PureTryOut noted, this is currently in Alpine's aports:
```
2018-03-07 13:42:56 <ncopa> awilfox: we have an issue with moving v4l-utils to community (commit 689327e79503480e774cff04560f8e4c695f5824)
2018-03-07 13:43:02 <ncopa> ffmpeg is in main and depends on v4l-utils
2018-03-07 13:43:06 <ncopa> this means that it is no longer possible to build everything in 'main' repo without also building 'community'
2018-03-07 13:43:11 <ncopa> it also means that we can no longer provide 2 year support for ffmpeg since one of its depends only have 6 month support
2018-03-07 13:44:29 <ncopa> we need to either move the entire reverse dependency chain over to community, or move qt5 to main
2018-03-07 13:44:52 <ncopa> qt5-qtbase should be enough
2018-03-07 13:48:53 <ncopa> hum, i think we can move the reverse deptree
```

I've tried to reproduce the issue right now by selecting another `aarch64` device and trying to install plasma mobile. For me it currently fails, because `ffmpeg-dev` was not built yet for `aarch64`. Looks like all we can do right now is waiting until the `aarch64` build bot is through here:

http://build.alpinelinux.org/

Sorry for the inconvenience, my guess is that it will work again in a few hours/tomorrow. Please note, that postmarketOS currently builds on the "edge" branch of Alpine (as in bleeding edge). Once postmarketOS gets more stable, it can rely on the stable branches of Alpine, which means there shouldn't be such breakage.

**Comment by Alexandroid99** [comment]
Well this is maddening... linux-firmware seems to be missing from edge as well, that's going to block my porting success if I can't get the vendor blobs to work and want to use the package instead...

**Comment by drebrez** [comment]
@Alexandroid99 I've just tried and the `linux-firmware` package and all it's subpackages are present in the alpine repository, maybe you are using an old mirror?
This is the default http://dl-cdn.alpinelinux.org/alpine/ and if you look [here](http://dl-cdn.alpinelinux.org/alpine/edge/main/armhf/) you will see the `linux-firmware-xxx` packages

**Comment by Alexandroid99** [comment]
Oh, I only looked on the search page for alpine packages. Nevermind then. :P

**Comment by ollieparanoid** [comment]
The package search requires wildcards if you want to search for a string inside the package name, e.g.:
https://pkgs.alpinelinux.org/packages?name=linux-firmware-*&branch=edge&arch=armhf

**Comment by ollieparanoid** [comment]
This should be resolved, `build-edge-aarch64` is idle right now.
