### ISSUE TITLE
Can't use the pmbootstrap newapkbuild

### ISSUE THREAD

**Issue by bhush9** [postmarketOS/pmbootstrap#1302]
```
(015477) [21:25:43] % tail -f /home/bshah/src/PostmarketOS/cache/log.txt -n 60
(015477) [21:25:43] *** output passed to pmbootstrap stdout, not to this log ***
(015485) [21:25:46] (native) % rm -r /home/pmos/build
(015485) [21:25:46] (native) % busybox su pmos -c 'mkdir -p /home/pmos/build'
(015485) [21:25:46] (native) % cd /home/pmos/build && busybox su pmos -c 'newapkbuild -n kwayland-integration -d KWayland integration -C -f'
(015485) [21:25:46] *** output passed to pmbootstrap stdout, not to this log ***
(015485) [21:25:46] (native) % busybox su pmos -c 'mv /home/pmos/build/kwayland-integration/src /home/pmos/build'
(015485) [21:25:46] (native) % busybox su pmos -c 'mv /home/pmos/build/kwayland-integration/APKBUILD /home/pmos/build'
(015485) [21:25:46] (native) % busybox su pmos -c 'mv /home/pmos/build/kwayland-integration/kwayland-integration /home/pmos/build'
mv: can't rename '/home/pmos/build/kwayland-integration/kwayland-integration': Directory not empty
(015485) [21:25:46] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(015485) [21:25:46] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/bshah/src/PostmarketOS/cache/log.txt
(015485) [21:25:46] ERROR: Command failed: (native) % busybox su pmos -c 'mv /home/pmos/build/kwayland-integration/kwayland-integration /home/pmos/build'
(015485) [21:25:46] Run 'pmbootstrap log' for details.
(015485) [21:25:46] See also: <https://postmarketos.org/troubleshooting>
(015485) [21:25:46] Traceback (most recent call last):
  File "/home/bshah/src/PostmarketOS/pmbootstrap/pmb/helpers/run.py", line 53, in core
    stderr=args.logfd)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '/usr/bin/sh', '-c', 'env -i CHARSET=UTF-8 PATH=/usr/lib/ccache/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin SHELL=/bin/ash HISTFILE=~/.ash_history /usr/bin/chroot /home/bshah/src/PostmarketOS/cache/chroot_native sh -c \'cd /;busybox su pmos -c \'"\'"\'mv /home/pmos/build/kwayland-integration/kwayland-integration /home/pmos/build\'"\'"\'\'']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bshah/src/PostmarketOS/pmbootstrap/pmb/__init__.py", line 61, in main
    getattr(frontend, args.action)(args)
  File "/home/bshah/src/PostmarketOS/pmbootstrap/pmb/helpers/frontend.py", line 224, in newapkbuild
    pmb.build.newapkbuild(args, args.folder, args.args_passed)
  File "/home/bshah/src/PostmarketOS/pmbootstrap/pmb/build/newapkbuild.py", line 51, in newapkbuild
    pmb.chroot.user(args, ["mv", path_inside, build])
  File "/home/bshah/src/PostmarketOS/pmbootstrap/pmb/chroot/user.py", line 34, in user
    auto_init, return_stdout, check)
  File "/home/bshah/src/PostmarketOS/pmbootstrap/pmb/chroot/root.py", line 86, in root
    return_stdout, check)
  File "/home/bshah/src/PostmarketOS/pmbootstrap/pmb/helpers/run.py", line 66, in core
    raise RuntimeError("Command failed: " + log_message) from exc
RuntimeError: Command failed: (native) % busybox su pmos -c 'mv /home/pmos/build/kwayland-integration/kwayland-integration /home/pmos/build'
```

Command used:

```
./pmbootstrap.py newapkbuild kde -n kwayland-integration -d 'KWayland integration' -C -f
```

(I also tried without -f)

**Comment by drebrez** [comment]
@bhush9 Error says that is not able to rename the directory `/home/pmos/build/kwayland-integration/kwayland-integration` because it's not empy.
I suppose something is wrong looking at the commands he performs:
```
mv /home/pmos/build/kwayland-integration/src /home/pmos/build
mv /home/pmos/build/kwayland-integration/APKBUILD /home/pmos/build
mv /home/pmos/build/kwayland-integration/kwayland-integration /home/pmos/build
```

**Comment by ollieparanoid** [comment]
I need to investigate this more, but what I found out so far is that the command works when slightly modified (no space in the description, pkgname at the end without `-n`):

```
pmbootstrap newapkbuild kde -d 'KWayland_integration' -C kwayland-integration
```

Thanks guys for reporting and analyzing!

**Comment by ollieparanoid** [comment]
```
Usage: newapkbuild [-n NAME] [-d DESC] [-l LICENSE] [-u URL]
       [-aCpy] [-s] [-cfh]
       PKGNAME[-PKGVER]|SRCURL
```
Okay, here's what I've figured out so far:
* Shell arguments in `pmb.chroot.user()` are not escaped properly, which is why the command fails when there is a space in the description.
* bugs/bad usability in `newapkbuild`:
  * using `-n` in combination with *not* specifying a `SRCURL` instead of the `pkgname` as last parameter does not make sense
  * not specifying the last parameter `PKGNAME[-PKGVER]|SRCURL` at all does not make sense either
* I think it makes sense to refactor the `newapkbuild` argument parsing so it does not pass through all arguments, but uses the usual argument parsing and build the command afterwards. Advantages:
  * we can easily fix the usability issues pointed out above, and do it instantly (while still upstreaming them as PRs to Alpine)
  * `pmbootstrap newapkbuild -h` is one help page that display all the flags, no need to run `pmbootstrap newapkbuild main -h`
  * same format as the other help pages
  * pmbootstrap doesn't enter the chroot just to display a help page
  * when we generate shell completion scripts from the argparse output at some point in the future, it will work with `newapkbuild` too.
  * the `-f` force flag is only relevant for the Python side, because we check if the aport exists outside of the chroots. If we control the argument parsing, we can just use the parameter in the wrapper Python code and not pass it to `newapkbuild`.

TODO:
- [ ] fix `pmb.chroot.user()` shell escaping
- [ ] handle `newapkbuild` arguments with `argparse` to properly require the last parameter, and only allow `-n` with `SRCURL`
- [ ] make upstream PR for requiring the last argument, and `-n` only with `SRCURL`

I've already started with the first two points, and I think I can finish it in the next days.

**Comment by ollieparanoid** [comment]
Shell escaping is fixed in merged PR #1316, better sanity checks for the arguments are in pending PR #1320.

**Comment by bhush9** [comment]
I'll take a look at #1316 later this week, sorry for delay.

**Comment by ollieparanoid** [comment]
Made a PR to upstream the same changes into Alpine's `newapkbuild` (when started without `pmbootstrap`): https://github.com/alpinelinux/abuild/pull/34

**Comment by ollieparanoid** [comment]
All TODOs from above resolved, closing :smiley:
