### ISSUE TITLE
Package abootimg

### ISSUE THREAD

**Issue by PabloCastellano** [postmarketOS/pmbootstrap#135]
This tool is already packaged in Debian.

It supports creating boot.img, descompressing and updating easily which can make development a lot easier.

* [Code](https://gitorious.org/ac100/abootimg)
* [README](https://gitorious.org/ac100/abootimg?p=ac100:abootimg.git;a=blob;f=README;h=8c1d6ddc005d22a1dd422ea98d2c4a9060315ad1;hb=HEAD)

**Comment by ollieparanoid** [comment]
As discussed in the IRC, I think this program does *not* have a *big* advantage over mkbootimg/unpackbootimg (which are already packaged). However, Linux distributions are about choice, and so is postmarketOS. If it is useful for you, please package it and create a PR!

My impressions:

*Advantages:*
* No Python dependency (good to keep the base install small, because right now, the fastboot-compatible devices depend on mkbootimg, and therefore Python) - maybe we would make this the default, if it proves to work as well as the official mkbootimg
* Properly versioned program (mkbootimg/unpackbootimg don't really have version numbers)

*Disadvantages:*
* Not "the official tool", so it might be incompatible (although I think this is unlikely as of now). If that happens, it will be really frustrating to find the cause when porting, because there are already a bunch of other reasons, why boot.img files could be broken.
* Not maintained since 2012 (...but as I understand it, the boot.img format hasn't changed since then either)

**Comment by ollieparanoid** [comment]
There were a few cases already where it made sense to suggest `abootimg` (because it repackages the boot.img without fully extracting it and rebuilding it), so it would be nice to have it packaged actually!
