### ISSUE TITLE
Ability to provide password and "copy your ssh key" via command line switch

### ISSUE THREAD

**Issue by z3ntu** [postmarketOS/pmbootstrap#1353]
This has been bothering me for a while now.

It would be great if you could specify in the `pmbootstrap install` command something like `--password=pw123` and `--copy-ssh-key=no` to eliminate the two prompts that exist in the `pmbootstrap install` command. The ssh key switch should be doable fairly easy because it's fully implemented in Python but the `passwd` command unfortunately doesn't accept a password as argument.

**Comment by drebrez** [comment]
@z3ntu there was an initial idea to move the `copy ssh key` question directly in the `pmbootstrap init`, see https://github.com/postmarketOS/pmbootstrap/pull/1327#issuecomment-372502277

**Comment by z3ntu** [comment]
@drebrez Also a good option.

**Comment by ollieparanoid** [comment]
If you just want to have any password set automatically, you could use `yes | pmbootstrap install` until we implement this as command-line switch (then the password is `y`). Unfortunately this will also answer the SSH key question with yes.

**Comment by craftyguy** [comment]
Setting password via a commandline option seems like a bad idea from a security standpoint. It'll show up in shell history, and it makes it too easy for someone to accidentally leak their password (e.g. by copy/pasting the pmbootstrap command they used when debugging some unrelated issue). I suggest instead having an env. variable that, when set, is used to set the password for the user on the device.

Instead of trying to call `passwd` to set it, why not create the hash and insert it into /etc/shadow directly, something like this: https://www.shellhacks.com/linux-generate-password-hash/

**Comment by z3ntu** [comment]
Yes, of course passing the password through a cmdline parameter is a security hazard but as I use the same password for my VMs anyways, it just improves my workflow of testing updated kernels. Generating the hash beforehand and maybe inserting it into the config could be a good option. (maybe activated by a `--expert` switch in the init command and asking the password there, hashing it and putting it into the config?

**Comment by drebrez** [comment]
@z3ntu if it's just for test and you don't care about which password it it, is suggest using what ollieparanoid suggested, I'm also doing it that way when I just do test installations.
`yes | pmbootstrap install` and you will have the password set as `y`.
If we move the ssh key question in the init we will only have the password question in the install, then we can even use the `yes <string>` command specifying which password we want, without the need of an additional parameter or env variables
