### ISSUE TITLE
pmbootstrap installs unneeded firmware to device

### ISSUE THREAD

**Issue by sicelo** [postmarketOS/pmbootstrap#1385]
I notice that `pmbootstrap install` installs a lot of firmware that will not get used on the device. My target is Nokia-N900 and in the log I see installation of linux-firmware-i915, linux-firmware-ath9k, linux-firmware-amdgpu, among others, and a whole of other linux-firmware-* packages.

I think this behavior could be changed. I understand that sometimes we may want to use that firmware if, for example, we connect a device via USB host, but in general I doubt this firmware is needed on most devices, at least for sure on N900.

**Comment by ollieparanoid** [comment]
Which firmware files get installed depends on the device. In case of the N900, there's `linux-firmware` mentioned in `aports/device/device-nokia-n900/APKBUILD`. The `linux-firmware` package has been split up recently in Alpine, so it is possible to specify the subpackages you've mentioned instead of the meta-package which depends on all of them.

I agree that we should change all device APKBUILDs where `linux-firmware` is used. Could you make a pull request, that fixes this for the N900?

From reading up [here](https://elinux.org/N900), the only firmware subpackage needed should be:
`linux-firmware-ti-connectivity` (WiFi: wl1251-fw.bin and wl1251-nvs.bin)

(CC @craftyguy and @pavelmachek, do you know about more firmware files used for the modem?)

Thanks for opening this issue @sicelo!

**Comment by craftyguy** [comment]
Wifi definitely needs firmware, I don't recall firmware being loaded for the modem, but it's really difficult to determine if it's required without removing all firmware and trying to load things (unless someone knows of a better way?), since not all drivers will say "I am loading firmware XYZ now" in the log..

**Comment by ollieparanoid** [comment]
@craftyguy: at least from that page, it looks like the bluetooth firmware never made it to the official `linux-firmware`. Regarding cellular modem: are there simple test instructions somewhere, that whoever gives this a shot could try out? Then we would know if behavior changes or not after reducing the installed firmwares.

**Comment by craftyguy** [comment]
> Regarding cellular modem: are there simple test instructions somewhere, that whoever gives this a shot could try out?

Well basically if they can do what was described in [the N900 wiki page for initializing the modem and establishing a data connection](https://wiki.postmarketos.org/wiki/Nokia_N900#GPRS) without any linux-firmware packages installed, then that would confirm the modem does not require loading any extra firmware to operate.

**Comment by sicelo** [comment]
Yes, N900 currently only needs `linux-firmware-ti-connectivity`
I am not very familiar with alpine to know if that's available as a separate package or not ...

**Comment by ollieparanoid** [comment]
It is the very package name. I'm not sure if closing the issue was intentional, but it isn't really solved and if you don't want to work on it that's totally fine.

**Comment by sicelo** [comment]
Thanks. I will look at it later today. I don't know how it got closed (thought someone else did).

**Comment by drebrez** [comment]
Issue #1184 seems a duplicate

**Comment by sicelo** [comment]
i made the following change:
``diff --git a/aports/device/device-nokia-n900/APKBUILD b/aports/device/device-nokia-n900/APKBUILD
index 6d22e60..32f10f2 100644
--- a/aports/device/device-nokia-n900/APKBUILD
+++ b/aports/device/device-nokia-n900/APKBUILD
@@ -97,7 +97,7 @@ i3wm() {
 
 nonfree_firmware() {
        pkgdesc="Wifi firmware"
-       depends="linux-firmware"
+       depends="linux-firmware-ti-connectivity"
        mkdir "$subpkgdir"
 }`` 

but afterwards in log I get:
`(022633) [21:21:50] device-nokia-n900-nonfree-firmware: depends on: linux-firmware`

which makes me wonder what other file might be causing the dependency on `linux-firmware`

I will test further now that building for N900 is working again (#1408 )

**Comment by ollieparanoid** [comment]
I guess the package was not rebuilt. Either run `pmbootstrap build --force device-nokia-n900` (for usual testing) or increase the `pkgrel` (that needs to be done once in the PR) in the APKBUILD. Other than that the patch looks good :+1:

**Comment by sicelo** [comment]
Closing. Commit 4388c6614df5915d76bad09ba882b7e70b7bf255 fixes the issue
