### ISSUE TITLE
"deviceinfo_flash_offset_base" is required for HTC devices?

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#145]
We have removed it in #128 already, because the value isn't being reported by `unpackbootimg` and we thought it would not be necessary to specify it.
Now we have learned, that it is actually required for HTC devices, because its bootloader, `hboot`, has an offset hardcoded.

@drebrez reported in the IRC:
> it works to boot directly with fastboot boot -b 0x20000000 vmlinuz-htc-bravo initramfs-htc-bravo

@MartijnBraam said:
> it seems that hboot doesn't parse the boot.img files for the addresses but has it hardcoded
> for example: the nexus 9 https://github.com/andreiw/nexus9_demo

So now it looks like, we need to revert that change. However, I'd like to have a deeper understanding about that, can anyone help out?

(For now it is possible to run `pmbootstrap flasher export` and flash the image manually outside of pmbootstrap with `fastboot`.)

**Comment by ollieparanoid** [comment]
@drebrez started to write a guide on how to do it all *without* the `deviceinfo_flash_offset_base` variable, but then recommended that we add it again, because it would be easier to use. He recommended using the `abootimg` tool (#135) to find out the missing `deviceinfo_flash_offset_base` variable, that the `unpackbootimg` tool does not report.

after `abootimg` extraction:
```shell
cat boot.img-htc-bravo-base
20000000
```

This leaves us the following tasks:
- [ ] package `abootimg` (#135)
- [ ] re-introduce the `deviceinfo_flash_offset_base` variable in the code (new branch):
  - [ ] parse it
  - [ ] use it when creating the `boot.img` file with `mkbootimg`
  - [ ] use it in `fastboot boot`
  - [ ] add it to all fastboot compatible device's `deviceinfo` files again
- [ ] add it to the deviceinfo reference wiki page again
- [ ] update the documentation on how to extract the value with `abootimg` (-> use `abootimg` to extract all fastboot related variables)

---
@drebrez: Could you add your guide to this ticket anyway? So your work is not lost and will help to get a better understanding of this topic :+1:

**Comment by drebrez** [comment]
@ollieparanoid it's not really necessary to change the tool, also unpackbootimg extracts all the files correctly and we have the same result files with both. Which means that both extracts the `boot.img-base` file which contains the base address.

I was just saying that the abootimg console output during the operation is different from unpackbootimg, it prints out this: https://pastebin.com/bBthXtdK

There is also an improved version of mkbootimg: https://github.com/osm0sis/mkbootimg which prints out a lot more information (see https://pastebin.com/SejNSvcx)

So for me the tool doesn't really matter what we use since with all of them we get all the informations we need.

About the offset base, in the htc-bravo device it has an offset base of `0x2000000`, which is different from the default values used by fastboot and mkbootimg which is `0x1000000`.

For this reason I had to adapt the other offsets like this:
`BOARD_KERNEL_BASE` + `<kernel_base_address>` - `<fastboot_default_base>`
...
which in real values was:
`0x00008000` + `0x20000000` - `0x10000000` = `0x10008000` 

and write in the device info:
`deviceinfo_flash_offset_kernel="0x10008000"`

**Comment by drebrez** [comment]
The suggestion to add again the `deviceinfo_flash_offset_base` in the deviceinfo was to simplify the porting of new devices since it will be just get the values and write them in deviceinfo without having to calculate some differences.

The mkbootimg and fastboot both have that parameter and both by default they use `0x1000000`.

My idea was to have a default `deviceinfo_flash_offset_base` somewhere with the default value (`0x1000000`) and with the deviceinfo we can override it for the devices that need a different value.

**Comment by ollieparanoid** [comment]
So we had a working tool all along, we just didn't look in the right file... thanks for clarifying!

That version of `mkbootimg` seems to be perfect, it is still maintained and a fork of the last official C version, which would keep the installation of the base system smaller. I'll contact the author about tagging releases in his fork (sadly he has the "issues" feature disabled, so I need to write an e-mail instead of making a ticket), so we could package it cleanly in pmOS.

And also thanks for explaining how to calculate the values again, I understand it now :)

I would like to add the `deviceinfo_flash_offset_base` variable again, as soon as the `heimdall-partitions-in-deviceinfo` branch is merged (#144), because it added [support for optional 
variables](https://github.com/postmarketOS/pmbootstrap/pull/144/files#diff-7a09142696d7640450025be1562d4b10R158) in the deviceinfo already. We could use that and avoid a merge conflict.

**Comment by drebrez** [comment]
@ollieparanoid now that we merged, I will try to add the optional deviceinfo_flash_offset_base variable

**Comment by ollieparanoid** [comment]
cool! wait a second, I've also prepared a patch I intended to submit
