### ISSUE TITLE
Update Raspberry Pi kernels / Pi3 with aarch64

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#1507]
When PR #1501 is merged, it will be possible to install postmarketOS on the Raspberry Pi. We are using the Raspberry Pi kernels provided by Alpine Linux, which are all compiled for `armhf`. In the discussions we were wondering if we could use an `aarch64` kernel for the Pi 3 instead, and if the `armhf` kernels could use an update.

@yangxuan8282 wrote in https://github.com/postmarketOS/pmbootstrap/pull/1501#issuecomment-390457985:
> if we can create a PR to ask alpine upstream enable `CONFIG_DRM_VC4` for `linux-rpi`, then we can use drm backend for weston and plasma mobile( it did work on rpi, although quite slow, and tend to crash soon ), the drm backend should more stable then use the fbdev backend

and in https://github.com/postmarketOS/pmbootstrap/pull/1501#issuecomment-390506303:
> There are two blog about rpi3 Alpine 64bit kernel:
> 
> https://a-delacruz.github.io/ubuntu/rpi3-setup-64bit-kernel
> 
> https://a-delacruz.github.io/alpine/alpine-linux.html
> 
> He using the downstream kernel, and use the bcmrpi3_defconfig.

as well as in https://github.com/postmarketOS/pmbootstrap/pull/1501#issuecomment-390839284:

> just found a web site, if that record is correct, then we may have some clue to build raspberry pi 3 64 bit kernel for alpine/pmos
> 
> this [pages](https://kernelci.org/boot/bcm2837-rpi-3-b/) is for rpi3: 
> 
> seems we should able to boot rpi3 with mainline kernel: 
> 
> - `defconfig` (that is arch/arm64/configs/defconfig) in 64 bit mode, and after compare to raspberry pi [wiki](https://github.com/raspberrypi/linux/wiki/Upstreaming), that config file did already have rpi3 support
> 
> - `bcm2835_defconfig` in 32 bit mode
> 
> the rpi2 pages is [this](https://kernelci.org/boot/bcm2836-rpi-2-b/), for other rpi models ( like zero/zero w, A+, B+) I'm not quite sure, but `bcm2835_defconfig` maybe also works
> 
> the alpine `linux-rpi` is kind of outdated, which is still 4.9.y and missing some modules for pi
> 
> maybe we can build a new mainline kernel package for rpi family, based on `APKBUILD` of `linux-vanilla`, use `defconfig`, `multi_v7_defconfig` and `bcm2835_defconfig` as config file 
> 
> Downstream kernel from raspberry pi foundation maybe a better choices, since it should have better support, but I don't have clue how to build a alpine/pmos package with it.

There are two ways to approach this, one would be modifying the (upstream sources of the kernel) `linux` package to boot on the Raspberry Pi. The other is improving the [downstream kernel](https://github.com/raspberrypi/linux) that is packaged already in Alpine's `linux-rpi` package.

Note that in contrary to Android downstream kernels, the Pi kernel is still maintained and rebased regularily on the newest Linux versions from upstream. The first way is much easier, so I would recommend to improve the downstream kernel packaging as a first step, and maybe look into using the upstream kernel in the future.

With that in mind, I think we can break down the research you did there in the following tasks:
- [ ] copy the `main/linux-rpi` folder from Alpine's aports to `pmbootstrap/aports/temp/linux-rpi`
- [ ] build it once just to make sure it works: `pmbootstrap build linux-rpi`
- [ ] enable `CONFIG_DRM_VC4` and test it
- [ ] update the kernel sources to 4.14 of the downstream kernel (`linux-vanilla` in Alpine is on 4.14 as well) and test it
- [ ] modify the package to build for `aarch64` as well:
  - [ ] add aarch64 to arch= in the APKBUILD
  - [ ] copy the kernel config config-rpi2.armhf to config-rpi2.aarch64
  - [ ] `pmbootstrap build --arch=aarch64 linux-rpi`
  - [ ] test it
- [ ] when everything is working, make a PR to Alpine with the changes

@yangxuan8282: does that make sense, and do you want to give it a shot?

**Comment by yangxuan8282** [comment]
for enable vc4, I have created a PR to upstream: https://github.com/alpinelinux/aports/pull/4337, still wait them check it, after they merged it the first three tasks are done

as for the rest tasks, we just need to modified the APKBUILD, since the config file should already works

if we use downstream kernel, the config file will use:

- [bcmrpi_defconfig](https://github.com/raspberrypi/linux/blob/rpi-4.14.y/arch/arm/configs/bcmrpi_defconfig) - RASPBERRY PI 1, PI 0, PI 0W, AND COMPUTE MODULE
 can be rename to `config-rpi.armhf`
- [bcm2709_defconfig](https://github.com/raspberrypi/linux/blob/rpi-4.14.y/arch/arm/configs/bcm2709_defconfig) - RASPBERRY PI 2, PI 3, AND COMPUTE MODULE 3
 can be rename to `config-rpi2.armhf`
- [bcmrpi3_defconfig](https://github.com/raspberrypi/linux/blob/rpi-4.14.y/arch/arm64/configs/bcmrpi3_defconfig) - RASPBERRY PI 3, PI 3 PLUS 64 BIT MODE
 can be rename to `config-rpi3.aarch64`

but there are some changes since the `linux-rpi` released, for example `firmware_install` have been delete in this [commit](https://github.com/raspberrypi/linux/commit/9e09007486c883de4aa78a384e1d54c3fe6e42d5) , so we have to change the way install the firmware, and I don't really understand why the `linux-rpi` not use downstream kernel as sources, instead, he diff from the upstream and downstream to generate a patch

if use mainline kernel, the config file:

- ? [bcm2835_defconfig](https://github.com/torvalds/linux/blob/master/arch/arm/configs/bcm2835_defconfig) - RASPBERRY PI 1, PI 0, PI 0W, AND COMPUTE MODULE (not sure)
 can be rename to `config-rpi.armhf`
- [multi_v7_defconfig](https://github.com/torvalds/linux/blob/master/arch/arm/configs/multi_v7_defconfig) - RASPBERRY PI 2, PI 3, AND COMPUTE MODULE 3
 can be rename to `config-rpi2.armhf`
- [defconfig](https://github.com/torvalds/linux/blob/master/arch/arm64/configs/defconfig) - RASPBERRY PI 3, PI 3 PLUS 64 BIT MODE
 can be rename to `config-rpi3.aarch64`

the `linux-vanilla` is more up to date, I guess need less modification

for other function on rpi, 

- [x] bluetooth (can be discovered, not test audio)
- [x] Wi-Fi
- [x] waveshare35b 3.5inch SPI LCD ( works)
- [ ] GPIO and serial not test yet

and now most rpi models should boot with pmos except the new raspberry pi 3b+(need update kernel to 4.14.y), although I just test on rpi3, but it's basically same as rpi2 when use 32 bit mode, will test zero w tomorrow and report

**Comment by ollieparanoid** [comment]
Awesome work! :tada: 

> I don't really understand why the linux-rpi not use downstream kernel as sources directly, instead, he diff from the upstream and downstream to generate a patch

ncopa answered a smilar question in https://github.com/postmarketOS/pmbootstrap/pull/285#issuecomment-319093977:
> We do it to save space and bandwidth usage. the 4.9 kernel has had 40 updates (4.9.40) the full linux source is around 90MB so the 40 releases would use 3.6GB in total. multiply that with number of build servers for the various architectures.
> 
> By adding a few lines of shell code that bandwidth and disk usage could easily be saved.

**Comment by yangxuan8282** [comment]
@ollieparanoid 
just test pmos on rpi zero w this morning, it boot success

**Comment by yangxuan8282** [comment]
@ollieparanoid 

here is my effort to update kernel: https://github.com/yangxuan8282/tmp-build

the config file is from archlinux arm

but it not work, can't boot alpine on rpi3, I don't have many experiences on compile kernel, so not really know how to get it work, need help from experienced user 

BTW, this package is not compiled by pmbootstrap, got a issues:

```
>>> linux-raspberrypi: Applying rpi-4.14.39-alpine.patch...
>>> linux-raspberrypi: Applying issue-4973.patch...
make: Entering directory '/home/pmos/build/src/linux-4.14'
make[1]: Entering directory '/home/pmos/build/src/build-raspberrypi'
getconf: LFS_CFLAGS: unknown variable
getconf: LFS_LDFLAGS: unknown variable
getconf: LFS_LIBS: unknown variable
  HOSTCC  scripts/basic/fixdep
  GEN     ./Makefile
/home/pmos/build/src/linux-4.14/scripts/basic/fixdep.c:105:23: fatal error: sys/types.h: No such file or directory
 #include <sys/types.h>
                       ^
compilation terminated.
make[2]: *** [scripts/Makefile.host:102: scripts/basic/fixdep] Error 1
make[1]: *** [/home/pmos/build/src/linux-4.14/Makefile:468: scripts_basic] Error 2
make[1]: Leaving directory '/home/pmos/build/src/build-raspberrypi'
make: *** [Makefile:146: sub-make] Error 2
make: Leaving directory '/home/pmos/build/src/linux-4.14'
>>> ERROR: linux-raspberrypi: all failed
```

I compile it with this [docker](https://github.com/yangxuan8282/docker-apk-build) on rpi.

**Comment by ollieparanoid** [comment]
> the config file is from archlinux arm

Why don't you use the config from the Alpine package and only increase the kernel version, maybe that is the reason why it did not work?

> `fatal error: sys/types.h: No such file or directory`

I think this is because `linux-headers` is not in your makedepends, see:

https://github.com/alpinelinux/aports/blob/e5080061370a133e1f8a2a2b1b42f96e9a7f6eb3/main/linux-vanilla/APKBUILD#L14-L15

**Comment by yangxuan8282** [comment]
@ollieparanoid 
I have compiled the linux-rpi upgrade to 4.14.39 (kind of outdated, the latest is 4.14.42, will update after figure out how to fix wifi), here is the links: https://github.com/yangxuan8282/rpi-aports/tree/master/testing, and there is a pkg there

that basically use the alpine config, but with vc4 and udl enabled, the problem is now wifi won't work even with `brcmfmac` and `b43` modules loaded, use `ifconfig` or  `iw list` to check, there are no wireless interfaces, and in dmesg also no wireless devices info. The drivers: brcmfmac43430-sdio.txt and brcmfmac43430-sdio.bin exist in /lib/firmware/brcm, so not sure what have missed.

as for the compiling issues on pmbootstrap, even include linux-headers still got same issues, and the alpine upstream linux-rpi not have that depends

**Comment by yangxuan8282** [comment]
I have fixed the wifi issues, seems we have working 4.14.y kernel for rpi now
after search in raspberrypi/linux issues, find a  similar issues: https://github.com/raspberrypi/linux/issues/2132 
In my dmesg output, there is no `mmc1` related info, so the wifi not exist issues was related to mmc in kernel. After compare to archlinux arm raspberrypi config file, I didn't set `CONFIG_MMC_BCM2835_MMC`, which make me wonder why previous alpine linux-rpi config file work no problem with wifi, it turn out that the options was renamed from linux 4.9 `CONFIG_MMC_BCM2835` to 4.14 `CONFIG_MMC_BCM2835_MMC`

after enable this, I recompiled the kernel, and tested on rpi3 and 3b+, it seems everything is work, except the 3b+ can't connect to 5G wifi, and the `linux-firmware-brcm` need to include those three files:
https://github.com/RPi-Distro/firmware-nonfree/raw/master/brcm/brcmfmac43455-sdio.bin
https://github.com/RPi-Distro/firmware-nonfree/raw/master/brcm/brcmfmac43455-sdio.clm_blob
https://github.com/RPi-Distro/firmware-nonfree/raw/master/brcm/brcmfmac43455-sdio.txt 

as for 64bit support for rpi 3b/3b+, I have checked the `config-vanilla.aarch64` of upstream `linux-vanilla`, seems it already have include some pi support, maybe we can boot it with it.

**Comment by ollieparanoid** [comment]
See my comment in https://github.com/postmarketOS/pmbootstrap/issues/1508#issuecomment-392265978 on thoughts how to package this for postmarketOS/Alpine now.

Regarding 5GHz Wifi, I guess comparing more against how other distros do it (if it works there) should help.

Everything you've found so far out is incredible, congratulations! :tada: :tada:

**Comment by yangxuan8282** [comment]
I will still trying to package latest rpi kernel, and add support for rpi 3/3b+ 64bit kernel later , but I guess there are only little chance the PR will be merged by upstream, so I tend to keep it as private daily use, but we can give APKBUILD links in raspberry pi pmos wiki pages for those want to try it.

**Comment by ollieparanoid** [comment]
> so I tend to keep it as private daily use

Uh, how about we at least upstream this to `pmbootstrap`'s `master` repository? That way it would be much more accessible to all the raspberry pi users on pmOS, and possibly others could update and maintain the packages as well.

**Comment by yangxuan8282** [comment]
Then should we keep this kernel still use the name linux-rpi, or rename it to another one? Like linux-raspberrypi or linux-raspberry-pi. I think use same name would be better for device package, but not sure if it conflict with the upstream one if different version exist in pmOS repo and Alpine repo.

**Comment by ollieparanoid** [comment]
I think we can use the same name, because we intend to update the package version. pmbootstrap/apk will pick the higher version, and if the version is equal, then the postmarketOS package because the pmOS repo is at the top of `/etc/apk/repositories`.

**Comment by yangxuan8282** [comment]
Thanks for explain, then I will create a PR to pmOS about linux-rpi later.
The latest version in my repo is 4.14.43, and I didn't use the Alpine upstream way generate diff between upstream and downstream, instead I use downstream as source directly. The 4.14.39 still use the patch way to get kernel source.
https://github.com/yangxuan8282/rpi-aports/blob/master/linux-rpi/APKBUILD

**Comment by yangxuan8282** [comment]
since the upstream linux-rpi add aarch64 support now, maybe we should close this issues
I have a question, can we add two arch (armhf, aarch64)into `deviceinfo_arch` of deviceinfo?

**Comment by ollieparanoid** [comment]
Yes. Related: https://github.com/postmarketOS/pmbootstrap/pull/1543#issuecomment-397004071

> I have a question, can we add two arch (armhf, aarch64)into `deviceinfo_arch` of deviceinfo?

That is not supported. To generate a new device aport: `pmbootstrap aportgen device-raspberry-pi-3b+`.
