### ISSUE TITLE
Package Plasma Mobile (KDE)

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#161]
I won't be working myself on this any time soon (see my personal [Milestones](https://github.com/postmarketOS/pmbootstrap/wiki/Milestones#ollieparanoid)), but nevertheless let's write down the steps that need to be taken to get this going.
If someone wants to give it a go, talk to @bhush9 (bshah in the channel) for upstream support from plasma mobile, and as always feel free to ask about any problems regarding pmbootstrap/postmarketOS. It would even help if someone started and made only little progress, as long as it is documented properly (as we usually do), so the next person can continue from there.

Steps:
1. Write down a list of packages (a table in a dedicated wiki page would be good, so we could put the status for each package there!), that need to be packaged for Alpine/pmOS. First I suggest packaging everything in pmOS, we can upstream what makes sense to Alpine later. The easiest way is to translate PKGBUILDs for Arch Linux to APKBUILDs from Alpine, they are very similar anyway!
Sources for PKGBUILDs:
* [Plasma mobile related](https://github.com/blue-systems/pm-arch/tree/master/packages)
* [Plasma related, and other dependencies](https://www.archlinux.org/packages/?sort=&arch=x86_64&q=plasma&maintainer=&flagged=) (click on a package, then the "Source Files" link on the next page, on the top right in a box)
2. Package all of them for pmOS. Make sure, that they all compile. Suggestion: create PRs for a few packages at I time, so they land in the official pmbootstrap repository pretty soon
3. Actually test on the phone, write documentation
4. Upstream what makes sense to Alpine Linux (talk to them in #alpine-devel on freenode's IRC server, you can also join this via matrix).

Other interfaces are listed in #62.

**Comment by PureTryOut** [comment]
So, I've been working a bit on this, getting a list of all the required dependencies and what not. I've also been trying to build a few of them, I'll submit them soon. The dependencies listed are dependencies of packages not packaged by Alpine.

This list probably still misses a lot, so it's subject to change. It's a good base to start with though. The list is based on [this Arch repository](https://github.com/blue-systems/pm-arch/tree/master/packages).

Required packages | Dependency of | Packaged by Alpine | Compiles
-------------------------|---------------------|---------------------------|-------------
plasma-mobile | | no | ?
baloo | plasma-mobile | no | ?
kdoctools | plasma-mobile | no | ?
kfilemetadata | baloo | no | ?
kidletime | baloo | no | ?
kio | baloo | no  | ?
lmdb-dev | baloo | yes |
qt5-qttools-dev | baloo, kfilemetadata, ki18n, karchive | yes
ki18n | kdoctools, kfilemetadata | no | yes
karchive | kdoctools, kfilemetadata | no | yes
docbook-xsl | kdoctools | yes | 
poppler-qt5 | kfilemetadata, okular-frameworks | Not entirely sure. There is a package "poppler", but it doesn't seem to include qt5 | ?
taglib-dev | kfilemetadata | yes | 
ebook-tools-dev | kfilemetadata | yes |
catdoc | kfilemetadata | no | [no](https://github.com/postmarketOS/pmbootstrap/issues/187)
qt5-qtdeclarative-dev | ki18n, libqofono-qt5, plasma-maliit-framework, plasma-maliit-plugin, ubuntu-accounts-qml-module | yes |
py3-qt5 | ki18n | yes |
qt5-qtscript-dev | ki18n | yes for all architectures, except armhf due to a build failure. It however compiles fine now | yes
qt5-qtbase | karchive | yes |
calamares-branding | | no | ?
calamares | calamares-branding | no | ?
qt5-qtsvg-dev | calamares | yes |
qt5-qtwebkit-dev | calamares | yes |
boost-dev | calamares | yes | 
parted | calamares | yes |
yaml-cpp-dev | calamares | yes |
koko | | no | ?
kpeoplevcard | | no | ?
kwinwrapper | Not entirely sure if required, as the [PKGBUILD](https://github.com/blue-systems/pm-arch/blob/master/packages/kwinwrapper-git/PKGBUILD) states this is required for Arch Linux specifically | no | ?
libqofono-qt5 | | no | ?
okular-frameworks | | no | ?
kpty | okular-frameworks | no | ?
kdelibs4support | okular-frameworks, plasma-settings | no | ?
threadweaver | okular-frameworks | no | ?
kactivities-frameworks | okular-frameworks | no | ?
khtml | okular-frameworks | no | ?
chmlib | okular-frameworks | no | ?
djvulibre | okular-frameworks | no | ?
libspectre | okular-frameworks | yes |
plasma-angelfish | | no | ?
plasma-framework | plasma-angelfish, plasma-camera, plasma-samegame, plasma-settings | no | ?
qt5-qtwebengine | plasma-angelfish | no | ?
plasma-camera | | no | ?
plasma-maliit-framework | plasma-maliit-plugin | no | ?
kwayland | plasma-maliit-framework | no | ?
plasma-maliit-plugin | | no | ?
plasma-phone-components | | no | ?
plasma-workspace | plasma-phone-components | no | ?
kpeople | plasma-phone-components | no | ?
telepathy-qt5 | plasma-phone-components | no | ?
qt5-graphicaleffects | plasma-phone-components | yes |
plasma-samegame | | no | ?
plasma-settings | | no | ?
libkgapi | plasma-settings | no | ?
ubuntu-accounts-qml-module | | no | ?
libaccounts-qt5 | ubuntu-accounts-qml-module | no | ?
signon | ubuntu-accounts-qml-module | no | ?

**Comment by craftyguy** [comment]
Can you put this table on this wiki so it can be edited by others?

**Comment by ollieparanoid** [comment]
That must have been lots of work, amazing!
*FYI: I've written a [short guide](https://github.com/postmarketOS/pmbootstrap/wiki/Creating-a-package) on how to create/port packages.*

**Comment by craftyguy** [comment]
@ollieparanoid your short guide is really great. that would have been useful a few days ago ;)

**Comment by craftyguy** [comment]
@PureTryOut 
For the packages that "compile", are you submitting each one, with APKBUILD?, somewhere?

**Comment by PureTryOut** [comment]
Planning too. I'm first trying to get a base working. Although I guess I could PR them as a WIP.

**Comment by PureTryOut** [comment]
I got everything up to plasma-framework building, so I'll submit that first and we can continue working from there.

**Comment by PureTryOut** [comment]
Update: got everything up till and including `plasma-workspace` to compile. I think I only have 2 packages left for a basic working shell. I will submit what I have now after the last cross compilation is done.

**Comment by ollieparanoid** [comment]
I'm closing this, thanks to our hero @PureTryOut we have at least the very basic components of plasma mobile packaged now \o/
And I'll open up another ticket with the state of actually getting plasma running (yes, we want that, too).
