### ISSUE TITLE
How to determinate flash offsets

### ISSUE THREAD

**Issue by MartijnBraam** [postmarketOS/pmbootstrap#18]
I've got my nexus 5 kernel to compile, the thing I don't have yet is the deviceinfo_flashoffset stuff. How are these calculated?

I have the output from boot_info for the original boot.img for the nexus 5:

```
./boot_info image-hammerhead-m4b30z/boot.img                                                                                                              ⏎
Page size: 2048 (0x00000800)
Kernel size: 8454264 (0x00810078)
Ramdisk size: 916830 (0x000dfd5e)
Second size: 0 (0x00000000)
Board name: 
Command line: 'console=ttyHSL0,115200,n8 androidboot.hardware=hammerhead user_debug=31 maxcpus=2 msm_watchdog_v2.enable=1'
Base address: 40894208 (0x026fff00)
```

The issues is that my numbers seem a few order of magnitude smaller than the ones in the samsung deviceinfo package.

**Comment by lawl** [comment]
This is untested because I'm still waiting for my battery, but here's is how (I believe I got the correct) offsets for the Galaxy Nexus: https://github.com/xiaolu/mkbootimg_tools which seems to report all the info needed when extracting a boot.img, well, except second_offset wasn't reported in my case, I "fixed" this by simply removing line 88 here: https://github.com/xiaolu/mkbootimg_tools/blob/master/mkboot#L88

Again, couldn't test it so far on my device, use at your own risk.

**Comment by ollieparanoid** [comment]
I can't really tell how these are calculated (they are somewhere in the Android sources I guess?)

However, I have packaged the [unpackbootimg](https://github.com/LineageOS/android_system_core/blob/cm-14.1/mkbootimg/unpackbootimg) Python script from LineageOS for postmarketOS, which can show the required information. Here's a guide:
https://github.com/postmarketOS/pmbootstrap/wiki/How-to-find-device-specific-information

If someone knows, how to get the offsets directly from the source repos, please adjust the guide.

@lawl: these mkbootimg_tools seem to use binary blobs, so I would not recommend that.
