### ISSUE TITLE
Failure to build package, commands are being executed twice

### ISSUE THREAD

**Issue by PureTryOut** [postmarketOS/pmbootstrap#187]
Trying to build a package called "catdoc" (dependency of something else I'm trying to install). Running Alpine's abuild command or `./pmbootstrap build catdoc` fails while manually running the commands in the APKBUILD works fine.

Also, a lot of commands are executed twice when ran via pmbootstrap, although this does not make it fail. This does not happen when manually running `abuild -r` from inside the chroot.

APKBUILD:
```
pkgname=catdoc
pkgver=0.94.2
pkgrel=1
pkgdesc="A convertor for Microsoft Word, Excel, PowerPoint and RTF Files to text"
arch="all"
url="http://www.wagner.pp.ru/~vitus/software/catdoc/"
license="GPL"
depends="glibc"
optdepends="tk: for using wordview"
options="!makeflags"
#source="http://ftp.de.debian.org/debian/pool/main/c/catdoc/${pkgname}_$pkgver.orig.tar.gz"
source="http://ftp.wagner.pp.ru/pub/catdoc/catdoc-$pkgver.tar.gz"

build() {
  cd "$srcdir/$pkgname-$pkgver"
  #sed -i 's/$(prefix)/$(installroot)$(prefix)/' desktop/Makefile.in
  #sed -i 's/0.94.2/0.94.4/' configure* doc/*.1 src/makefile.tc
  ./configure --prefix=/usr  --with-wish=/usr/bin/wish
  make
}

package() {
  cd "$srcdir/$pkgname-$pkgver"
  make installroot="$pkgdir" mandir=/usr/share/man/man1 install
  install -d "$pkgdir/usr/share/man/man1"
  install -m644 doc/*.1 "$pkgdir/usr/share/man/man1"
}
sha512sums="d1772ba8977b7d99febd0a34e0660a169eea7c91c873baeab0e290c448a66cfacc3ad7d8927c4cae0106af4b41bac1e66492fec743a6406d70a7e0df6f418a56  catdoc-0.94.2.tar.gz"
```

Complete build log: https://bpaste.net/show/e5908c5b1571

**Comment by PureTryOut** [comment]
The interesting part is that when I run those commands in the chroot without using any Alpine tools, so just literally what it says in the APKBUILD, everything builds fine.

**Comment by ollieparanoid** [comment]
Thanks for making this ticket!

I can not reproduce the "building twice" issue with the APKBUILD you have provided, I guess it could go away after zapping your chroot and trying again?

### Do we need this for Plasma Mobile?
You have listed it as dependency of [`kfilemetadata`](https://www.archlinux.org/packages/extra/x86_64/kfilemetadata/). But it says on that page, that it is optional and only needed to *extract text from office 98 files*, which is far from our use case of having a functional phone UI.

Arch tries to provide all packages as vanilla as possible, which usually means that a program has all features enabled. I suggest that for pmOS, at least for packaging plasma mobile, we focus on the features we really need (and in my opinion, previews for ancient office formats is not one of them). Besides I feel uneasy about *old* C code, because it usually is easy to exploit (the author says that a *lot of segfaults on incorrect or corrupted data* were fixed in the [latest version](http://www.wagner.pp.ru/~vitus/software/catdoc/changelog.html) though, but of course it is better to entirely avoid this if possible).

### Packaging
* Please use the latest version of software (`0.95` in this case)
* manpages and other documentation goes into an extra `-doc` package in Alpine, and `abuild` will complain if the main package contains them. The solution is to add this: `subpackages="$pkgname-doc"` ([more info](https://wiki.alpinelinux.org/wiki/APKBUILD_Reference#doc.28.29))
* APKBUILD has different [options](https://wiki.alpinelinux.org/wiki/APKBUILD_Reference#options) (!makeflags won't work afaik, but it has !strip and !check)
* APKBUILD does not have `optdepends`, see [APKBUILD Reference](https://wiki.alpinelinux.org/wiki/APKBUILD_Reference)


### Thank you!
Don't get me wrong here, I was really happy to see that you have picked the plasma mobile packaging and are working on this and I will support you wherever I can :+1: 

Also if you say you'd need this package anyway I would help you until it works. Otherwise, I suggest you `pmbootstrap zap` your chroot (to avoid having follow-up errors) and close this ticket.

**Comment by PureTryOut** [comment]
Good call, I didn't think about Arch packaging *everything*. I'll recheck the full Plasma Mobile list and see what can go.

I did figure out the `-doc` part, I updated the build log to reflect the actual error it breaks on.
