### ISSUE TITLE
Separate folders for devices & packages under aports 

### ISSUE THREAD

**Issue by kskarthik** [postmarketOS/pmbootstrap#194]
Since, number of supported devices are growing, also more packages are planned to be added in future (plasma-mobile) I suggest that we need to separate the device builds from the packages. 

Does it create any problems from code level?

**Comment by PureTryOut** [comment]
Since I started packaging plasma-mobile, I'd really love to have this. Because [the list of packages required](https://github.com/postmarketOS/pmbootstrap/issues/161#issuecomment-316304383) to package is so big, the `aports/` folder will otherwise get really cluttered.

**Comment by ollieparanoid** [comment]
That sounds like a great idea to me, it makes the aports so much easier to browse!
But yes, the code needs to be adjusted in a lot of places for that - currently it assumes, that the packages are directly in the aports folder.
(In case anyone is wondering, I would keep all packages in one APKINDEX.tar.gz for now, but it might make sense to split that up at some later point.)

**Comment by ollieparanoid** [comment]
Which directory structure do we want to have? Here is a suggestion:
```shell
aports/
    cross/ # cross-compiler related packages: *-armhf, *-aarch64, qemu-user-static
    device/ # everything device specific: device-* and device kernels
    main/ # everything else, mainline kernel
    ui-plasma-mobile/
    unmaintained/ # as the name says, alpine also has such a folder
```

A testing folder could also make sense (for an extra testing repo), but I recommend we do something like that in the future, when we have binary packages.

**Comment by MartijnBraam** [comment]
how about a `kde` folder instead of `ui-plasma-mobile` to not confuse it with the package name

**Comment by ollieparanoid** [comment]
`kde` would also be fine for me. Yeah it makes more sense, because it is the bigger term, that includes `plasma` according to [Wikipedia](https://en.wikipedia.org/wiki/Kde):
> The Plasma Desktop, being one of the most recognized projects of KDE [...]

**Comment by PureTryOut** [comment]
Do we actually need a preset folder structure? Or at least, do we need to handle that in code?

Can we not just check all packages in `aports/`, no matter how deep they go or where they are? I'm not sure how slow that would be if the list of aports becomes bigger, but that way you don't have to change the code if we decide to add another UI or someting.

**Comment by ollieparanoid** [comment]
Python 3.4, which we support for Debian Jessie, does not have recursive globs to start with. So it would need some additional code to allow an infinitely deep folder structure of aports.

I'm rewriting the code to find aports in `aports/*/$pkgname`, so the build part does not hardcode the specific subfolder name. However, the parts where we want to access specific aports do need a folder structure hardcoded:
* list of supported devices (-> `aports/device/device-*`)
* generated aports (-> `aports/cross/`)
* initramfs hooks
(these are the examples I can think of right now, there could be more.)

So we could theoretically rename the `kde` folder later on. But we should really not do that often, because it introduces merge conflicts and breaks weblinks if someone linked to a package in master (and not pressed `y` to get a link to the current commit instead). My suggestion is creating a relatively fixed folder structure now, that we will use and put in the wiki - and if we notice that it needs to be changed we do it carefully and not too often.

Moving packages between `unmaintained` and any other subfolder should be a normal usecase (and maybe later we could have a `testing` folder, where packages are tried for some time before becoming "stable").

**Comment by ollieparanoid** [comment]
@PureTryOut: Do we even need *multiple* subfolder levels for aports? That would be very uncommon compared to how other Linux distributions do it I think, and I can't see a benefit in it.

**Comment by PureTryOut** [comment]
Well I was thinking for example about this:

```
aports/
    cross/ # cross-compiler related packages: *-armhf, *-aarch64, qemu-user-static
    device/ # everything device specific: device-* and device kernels
    main/ # everything else, mainline kernel
    ui/ # common dependencies between UI's
        plasma-mobile/ # plasma-mobile specific aports (plasma-framework, plasma-workspace, etc)
        ubports/ # ubports specific aports
    unmaintained/ # as the name says, alpine also has such a folder
```

I might just be over thinking this, but it seems useful to me.

**Comment by ollieparanoid** [comment]
With the structure you have outlined, I think it would be hard to tell if "plasma-mobile" is a folder that contains more aports, or is an aport itself. So how about we keep the structure with *one subfolder level* for now (also with `kde` instead of `plasma-mobile`), and if we end up with too many folders on the first level, then we reconsider the approach and add multiple levels?

*Ideally we would never get *that many* folders anyway, if we manage to upstream our stuff properly to Alpine.*

**Comment by PureTryOut** [comment]
> Ideally we would never get that many folders anyway, if we manage to upstream our stuff properly to Alpine.

That last part is important. I guess it's fine with me, please go ahead!
