### ISSUE TITLE
Submit logo ideas/concepts here

### ISSUE THREAD

**Issue by antonok-edm** [postmarketOS/pmbootstrap#207]
Right now the postmarketOS logo is a stock recycling icon. We should put some thought into branding that can both reinforce the goals of the project and better attract potential developers or, later down the line, end users.
Any idea is helpful, even those regarding colors or fonts!

**Comment by antonok-edm** [comment]
Some ideas to consider:
-somehow distinguishing pmOS specifically as a mobile operating system
-would be cool to have two consistent logos for both "pmOS" and "postmarketOS"
-possibly continuing the "recycling" theme, as we are making would-be trash phones usable once again. Or maybe just "environmentally-friendly" - we are forking off Alpine (mountains?)
-maybe imply "lightness" or "speed" somehow? pmOS is supposed to run fast and lightweight
-should look modern since we are modernizing old hardware

**Comment by antonok-edm** [comment]
-openness - one of pmOS's goals is to help the user to know exactly what is running on their device, and the project is open source

**Comment by ollieparanoid** [comment]
Great suggestions so far, I like the matrix icon, with the recycle icon on top of a fat phone. Maybe we can use that somehow. @AndrewMcSwain also had some ideas about branding.

It would be great if we could use the font from the Alpine logo (if it is okay with them!)

**Comment by AndrewMcSwain** [comment]
I dont have a working computer right now and my python libraries aren't loading in termux, so my market research has slowed down a bit, but that aside, there's a lot that we need to understand before we start deciding these kinds of things. Logo ≠ branding. and what font is a question that we should only ask after we've done more research, otherwise you could be working in a direction that has no traction, no matter how cool we think it is. Marketing research doesn't need to be quanitative or even actionable at first, it just needs to give us perspective about their lightcone, first and foremost.

Let's try to categorize types of users. I've already started, (for ex: new user: non-IT doctoral students, highly mobile megacity entrepreneurs, mobile-loving teens, and adolescent west african  e-waste recyclers). Then i hypothesize use cases and evaluate these hypotheses by noting reactions during a product demo.

There are many categories to consider, each with their own set of 'conditions,' first, then understanding 1) immediate insertion strategies 2) the expected / ideal market development strategy.

Sorry it's hard to explain all this stuff in one go, but you need to know at least what the key words mean before you jump in, otherwise you'll waste a lot of time and just stunt the project to something gimicky and 'neat.'  'drawing a logo and picking a font' are not the first questions we should be asking.

Better,

Who are our user groups *today* ?
Who will they be in 12 months, 36 months, ... and so on?
[qualitative questions about them (do they care about recycling/upcycling? Do they care about security? Jedi or Sith? Did they read Neuromancer? Did they like one, none, or all 4 matrix movies? Do they meme? Where do they live? How many computers do they have? How many of them like pottery? Do they lile to travel or wish they could travel more? Do they go to an office and spend all day on their bum, hearing lumberg talking about tps reports? Do they wish their computing lifestyle were different? How? What's the population density where they live?  How is it zoned? Distance from home to work and distance from work to bar? Commute times. These are examples of the *kinds* of questions you should ask FIRST. Then we can build moodboards of themes and visual identities and maybe a rudimentary marketing plan. THEN we have enough ground to start making *****correct****** decisions about the details of a logo or the site header or whatever else. 

In the end, an enterprise in it's branding (again, branding≠logo) needs to be a coherent whole. Having a 'better' logo or a tediously selecting that perfect font is going to add zero [0] value to a project if those little details aren't part of a conistent identity.

**Comment by AndrewMcSwain** [comment]
Can we use a more organized and perhaps more discreet way of working on this, like a collective spreadsheet? 

i would very much prefer more empirically rigorous methods of parsing information, but here goes: @ollieparanoid, can you shine some light on this question of user categories, based on the responses you've gotten from the blog posts, your email, your private messages, forums, wiki activity, and discussions on content-aggregators?

What has the overall sentiment been from HN and reddit? Is there a commonality in the users that show specific types of responses? And of those who are, say, dismissive of the project, "who are they?" 

Who are the people who have said "Woah, I can't wait till I can use this" and who are the people who show up here and participate more regularly? What are some of the qualities of each group individually, and how are these groups related?

Let's examine the patterns of the flows of these 'potential users.'

**Comment by AndrewMcSwain** [comment]
as well as establish some hypothetical 'appeals' or reasons (psycho-emotive and rational (game theory) that each user group relates to the brand/product in a particulary way. These questions are super-shallow, and truly effective marketing will dig in even further, but we need to work from first principles and iterate over the set.

**Comment by ollieparanoid** [comment]
@AndrewMcSwain, the comments to the various blog posts are numerous and all public, so everyone could go and make a user study out of them (I have linked them at the end of each article, and I believe you have already started anyway?). I'm glad if I can get some coding done besides doing support and fixing bugs, so user profiles is something I won't look into any time soon, sorry.

You seem to be the expert here. If you say spreadshirt, I'd suggest creating an [ethercalc](https://ethercalc.net/) sheet and putting the spreadsheet link in this issue. Other than that I think wikis can be nicely structured! How about a new wiki in a new `postmarketOS/branding` repository? There everyone could also upload logos and related self-created content regarding branding.The important thing is, that it *has* a good structure and its results are easily accessible.

*From my engineer view, I think having a good looking logo is better than no logo, even if it does not have any marketing potential. We could change it when the branding and everything evolved, right?*

What do you guys think?

**Comment by antonok-edm** [comment]
@AndrewMcSwain wow, it's great to have someone with so much expertise with this. I imagined we'd kind of be stumbling along with these aspects but it looks like you could save us :)

I definitely agree that it's important to know our target audience for this but I'm not sure we have *that* good of an idea at this early point anyways. We can sort of make some guesses, but for now, we basically just need developers with old phones...

My original idea is exactly echoed by @ollieparanoid's last paragraph. The whole project is really a WIP so far and I think it's acceptable to "evolve" an image as we continue to develop the code. I was hoping to collect feedback here from contributors at least, but the spreadsheet organization with some info on other demographics certainly seems like a better idea.

I think for now, having some kind of symbol to call our own and identify with would at the very least lend the project some extra legitimacy. We already are being talked about at e.g. the KDE meetup, it would be awesome if people could think of us as a team working on a project rather than a bunch of code someone threw together.

Just my (perhaps naive) view on this.

**Comment by ollieparanoid** [comment]
@MartijnBraam proposed a logo in https://github.com/postmarketOS/postmarketos.github.io/pull/5
