### ISSUE TITLE
init function should validate user input

### ISSUE THREAD

**Issue by craftyguy** [postmarketOS/pmbootstrap#242]
It is currently possible to run `pmbootstrap init` and enter arbitrary values into the prompts. This function should validate that the user's input is a valid input for the given prompt, based on a set of acceptable values. Perhaps `pmb.helpers.cli.ask` can be extended to also include passing a set of valid input values, and in the case of an invalid value entered by user it can provide an error, reprint acceptable values, and re-prompt until the user gets it right.

**Comment by craftyguy** [comment]
#241 is one example of a user that was allowed to enter 'invalid' input during `init` and later hit an error because of it (validity of that input actually depends on whether or not we want to allow case sensitive device package naming, #244 )

**Comment by ollieparanoid** [comment]
Thanks for opening this issue. Here are the questions we ask in `pmbootstrap init`:

1. Target device -> format `vendor-codename` (both vendor and codename are lowercase and should only contain a-z and numbers)
2. Work folder -> this could be anything! no validation makes sense here, or am I wrong? If the folder can't be created, the script fails directly after asking this question anyway, because it tries to create that folder.
3. Parallel job count -> number >= 1
4. Timestamp based rebuilds -> y | n

As I see it, we could add a new parameter to `pmb.helpers.cli.ask` to verify the input against a regex, and then loop until the user types in something valid. We could then use that new parameter for 1, 3, 4 (not for 2).

Would this be a suitable fix?

**Comment by craftyguy** [comment]
Those proposals seem reasonable to me!
For the 2nd case, the work folder, if it fails it can re-prompt instead of just bailing out entirely. For this one, you'd have to basically try/catch the 'mkdir', and loop through prompt->mkdir->display error->prompt until they get it right.
