### ISSUE TITLE
Mount /boot in /etc/fstab somehow

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#255]
Could be done in `postmarketos-base` by label, so it should work for all devices.

(If other devices need to extend /etc/fstab, they could check if it was modified or not (with apk, as done in the `postmarketos-base` post-install hook), and append lines to it accordingly.)

**Comment by craftyguy** [comment]
What if this were to be handled by device packages instead of postmarketos-base? I can easily foresee devices (like the N900) with partitions/drives that other devices don't have (e.g. a pre-existing swap & data partition on the N900). This seems simpler than trying to predict what devices would want, and then having the device packages develop new logic for extended it if the fstab from postmarketos-base is not what they want.

**Comment by ollieparanoid** [comment]
### Put it in `postmarketos-base`
Advantage:
* `/boot` would always be mounted consistently for all devices

Disadvantage:
* Additional mountpoints would need to be appended in a `post-install` script
* **Updating the `/etc/fstab` file wouldn't work anymore, once modified by such a `post-install` script.**

### Put it in `device-...`
Advantages:
* All device specific partitions could be mounted easily, such as SWAP on the N900

Disadvantages:
* We need to maintain a `/etc/fstab` file for all devices, even if they only need to have `/boot` mounted

## Conclusion
After putting some thought into this, **I think it is better to put it into the device package, as you said.** It shouldn't be that hard to maintain one `/etc/fstab` file per device - usually it would be copy pasting the initial file and then adjusting it *once* as necessary.


Related PR: #251

**Comment by craftyguy** [comment]
@ollieparanoid thanks for the feedback. In the spirit of "not removing existing config files" not  installed by the device package, I have modified #251 to basically append to the existing /etc/fstab only if the entry doesn't currently exist in it. This would allow for 'clean and safe'' upgrades to the device package without having a billion copies of the same mount point in fstab AND will also allow users to add any new mountpoints (e.g. ramdisks) they want and preserve their modifications since we're just appending to the file.

**Comment by craftyguy** [comment]
Given that #251 is merged now, is there any reason for keeping this issue open any longer? I have also added a note about this functionality to [the device porting wiki page](https://github.com/postmarketOS/pmbootstrap/wiki/Porting-to-a-new-device)

**Comment by ollieparanoid** [comment]
Nope, there's no reason. Thanks for reminding me, I'm happy when we can keep the issues count free of already finished tickets (so the count doesn't rise up endlessly, and it stays feasible to look through the open tickets).
