### ISSUE TITLE
Drop to shell in initramfs instead of looping forever

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#277]
Suggested by @MartijnBraam in #257.
This will be useful for devices with a hardware keyboard or a serial cable attached.
I recommend waiting with this feature, until we have the other initramfs-PRs through (and possibly also the aports subfolders PR, which will change the folder structure in `aports`).

**Comment by PabloCastellano** [comment]
We have those PRs already merged so we can start working on this issue :smiley:

**Comment by craftyguy** [comment]
I'm willing to take this one, but I need some guidance on the design/functionality... Since all output is being redirected elsewhere (`/pmOS_init.log`), dropping to a shell is pretty much useless since you would never see the prompt, and there's currently no timeout or way to bypass the call to unlock the root partition.

So are you asking to have a way to flag devices with a HW keyboard to:

 1) not redirect output to a file and not start telnet so pass can be entered, or 

2) just simply replace the call to `loop_forever` in `init.sh.in` with a call to `/bin/sh`?

**Comment by ollieparanoid** [comment]
I would simply drop to a shell - we already have the `PMOS_NO_OUTPUT_REDIRECT` kernel parameter, which disables the redirection.

**Comment by craftyguy** [comment]
I'm thinking that if we're going to drop to shell, that we should also remove the redirection right before dropping to shell. It would be confusing/useless to drop to shell and have redirection to file still enabled, despite whether or not the user has remembered to set `PMOS_NO_OUTPUT_REDIRECT`. Thoughts?

**Comment by ollieparanoid** [comment]
Honestly I am not sure if that is even possible.
But let's say you have the `PMOS_NO_OUTPUT_REDIRECT` option not set. Then you get informed via print to stdout at the very beginning, that everything gets redirected to the log file, and you won't see anymore messages - it will just hang.
So as a user who sees this message on serial/in the N900/wherever, I would naturally enable the no-redirect option and try again (which then gives me more output *and* a working shell when it enters that state), or am I missing something?

**Comment by craftyguy** [comment]
I'm trying to prevent this from being required:

> I would naturally enable the no-redirect option and try again

Since that essentially requires a reflash, if you remember that you are in this situation in the first place because you cannot unlock rootfs, in order to set the no-redirect option in kernel cmdline.

Perhaps the no-redirect option should be enabled by default on the N900 and other devices with hardware keyboards (I never liked it anyways, since the log file goes away after switchroot, losing valuable debug info), but this would trash @MartijnBraam's amazing splash screen.

**Comment by MartijnBraam** [comment]
well on the n900 we can just add 2 boot menu options to boot normal and recovery (like what most linux distro's do with grub).

If we have the hardware support we can also make it check if the volume button is hold upon entering the initrd or something to switch debug mode

**Comment by ollieparanoid** [comment]
> Since that essentially requires a reflash, if you remember that you are in this situation in the first place because you cannot unlock rootfs, in order to set the no-redirect option in kernel cmdline.

Good thinking, I haven't looked at it from this point.

@MartijnBraam also has good points.

So for this ticket, I guess it depends how you want to put the balance between end-user-friendly and quick to implement.

Right now you may as well make a second entry in the boot menu for the N900, and for the other devices you would need serial to use the shell anyway, which would place you in the position to reflash the initramfs. So implementing it the easy way with just dropping to a shell + second boot menu entry in uboot for the N900 is the quick solution, which is still better than what we have now (no shell).

If you directly want to make the enduser friendly version, be my guest. But keep in mind, that there will be some drastic changes ahead in the initramfs, e.g. with the on screen keyboard.

**Comment by ollieparanoid** [comment]
This is an old issue by now. In the meantime, osk-sdl became the default unlocking method and we have a hook that always stops the boot process when installed: `debug-shell`

It provides a shell over telnet, and it drops to a shell locally on the device, if there's a working tty.

So what we have right now seems to be much better from a security point of view, than always dropping to a shell on errors. Closing.
