### ISSUE TITLE
[bullhead][fp2] Package and implement libsparse

### ISSUE THREAD

**Issue by MartijnBraam** [postmarketOS/pmbootstrap#299]
Package libsparse from the android project which provides the `img2simg` and `simg2img` commands.
These split a large image for the system partition into seperate smaller chucks with sparse headers.

This is required for at least the Nexus 5x and the Fairphone 2 (#245) because it fixes the `Invalid sparse file format at header magi` error.

https://android.googlesource.com/platform/system/core/+/refs/heads/master/libsparse/

**Comment by ollieparanoid** [comment]
As I see it, these are the TODOs:
- [ ] package libsparse
- [ ] add a new variable to the deviceinfo: `deviceinfo_flash_sparse`
- [ ] when that variable is set to true, convert the image to a sparse image after `pmbootstrap install`

**Comment by PabloCastellano** [comment]
Generating the sparse image works, but haven't tested flashing to any of the devices that need it.

**Comment by PabloCastellano** [comment]
- [x] Add to deviceinfo reference
- [x] Add to troubleshooting: [Invalid sparse file format at header magi](https://github.com/postmarketOS/pmbootstrap/wiki/Troubleshooting#invalid-sparse-file-format-at-header-magi)

**Comment by PabloCastellano** [comment]
Since I understand that https://github.com/postmarketOS/pmbootstrap/pull/303#issuecomment-319017197 is not under our control, we need to find a solution to where to get the libsparse code from.

Some options are:
- Clone the android-7.1.2_r6 branch of libsparse to GitHub, tag it and use it as source in APKBUILD
- Do not clone it ourselves but use someone else's repo (i.e.: [debian](https://sources.debian.net/src/android-platform-system-core/1:7.0.0%2Br33-2/libsparse/) or [anestisb](https://github.com/anestisb/android-simg2img))

I'd go for the first but want to know what do you guys think

**Comment by ollieparanoid** [comment]
anetisb's `android-simg2img` repository seems to already be what we need.

Looks like it is maintained well, and has a little community around it (look at the number of stars and forks in the repo). I'd prefer if we use that repository instead of starting yet another fork and have asked the author if they could start using release tags.

**Comment by PabloCastellano** [comment]
Ok, they have already tagged it. I'll change APKBUILD to use their version.

Besides that, there is also the [issue](https://github.com/postmarketOS/pmbootstrap/pull/303#issuecomment-319129996) that `img2simg` must be installed in the native chroot because we need to convert the system image which is already generated there. I may be missing something because the package is installed only in the device rootfs. What is the proper way to install a dependency in the native chroot when the package depends on it?

**Comment by PabloCastellano** [comment]
Concerning PR https://github.com/postmarketOS/pmbootstrap/pull/127, the sparse system image for my titan is 299MB after running `img2simg`. Not sure how it affects, but you first get asked to make sure the system partition has at least 850MB and then you would flash 299MB.

**Comment by ollieparanoid** [comment]
I suggest, that we name the package name after the upstream's repository to `android-simg2img` if it is okay with you.
About the installation problem:

* do *not* add the program to the device's depends (as it would not be needed on the device, it is just needed to prepare the installation image for flashing)
* use `pmb.chroot.apk.install()` to *build and install* the program in the native chroot, just when you need it in pmbootstrap (I've also added this as comment to your PR in the right location)

**Comment by PabloCastellano** [comment]
@ollieparanoid Thanks for your feedback. `libsparse` is now installed in the chroot and works fine for me (both the image generation and flashing to my titan). About the naming, I don't usually mind so much about the name of things (plus I'm really bad at naming things :stuck_out_tongue_closed_eyes: ) but in this case `android-simg2img` looks to me like a worse name since:

- The repository contains all the libsparse tools (not only simg2img)
- We don't even use at the moment `simg2img` (as part of `android-simg2img`), but `img2simg`!

Note for testers: I did a forced push

**Comment by yuvadm** [comment]
Regarding problems I'm seeing in #337, any chance we might be able to add the `ext2simg` tool? It's a bit choppy since we need to pull it from upstream (it was in Android extras until recently, then it moved upstream to e2fsprogs), but it could be useful, and possibly more stable.

**Comment by ollieparanoid** [comment]
I recommend moving the discussion to #337, because this isn't about `libsparse` anymore.

**Comment by z3ntu** [comment]
For the fp2 I have `deviceinfo_flash_sparse="true"` in the deviceinfo but not a dependency to libsparse. Compilation and booting still works fine (I use the recovery zip method)

**Comment by z3ntu** [comment]
Found #312 which is basically this issue described in my last comment.

**Comment by z3ntu** [comment]
I have actually packaged make_ext4fs but it's no longer neccessary as I have patched the Fairphone lk sources to support the CHUNK_FILL type in sparse images. Commit: https://github.com/z3ntu/android_kernel_lk_fairphone_FP2/commit/0255581a47b96b8b0b3d7c5f0336d5f6bef8f2ad (also found in several other lk sources e.g. on codeaurora).
I am hoping that the commit will be applied by Fairphone soon and be included in an upcoming release.
