### ISSUE TITLE
Device manufacturer specific comments in porting guide 

### ISSUE THREAD

**Issue by br0ke** [postmarketOS/pmbootstrap#318]
First I want to say thanks to all the people who work on this project.

Right now as you already know different manufacturers have a different take on how much control they should give to their users and different levels of openness regarding publishing their internals. People who want to contribute to the project will be well informed if we guide them through the habits of the manufacturer of various parts and the overall device manufacturer.

If everyone if okay with this, I think we should make the porting guide a more detailed version of what is exactly going on with pmbootstrap. Currently it assumes the potential porters have a very good understanding of the custom ROM ecosystem (I don't, and found navigating and understanding everything difficult). Even within the wiki there are some things which can be corrected. For example: 

1. [This](https://github.com/postmarketOS/pmbootstrap/wiki/samsung-S7562) page talks how there is a random github repo with the kernel source, but Samsung actually maintains a comprehensive [Open Source website](http://opensource.samsung.com/reception.do) where a search for the device model number will give the kernel and any updates. 

2. Samsung uses different SoCs depending on the date and the release line. If it is a Qualcomm SoC, then for the graphics driver, you'll have the [freedreno](https://github.com/freedreno/freedreno/wiki) reverse-engineered OSS driver, and if it is the ARM line, there's [lima](https://limadriver.org/) but it is less popular compared to FreeDreno. Pulling the drivers from here will be more in the spirit of opensource (if possible) rather than getting binary blobs.

I'm happy to start working on the porting wiki page and would appreciate any further commentary. 

Sidenote: Are there any plans of moving the guides of this repo's wiki? As I see there's a pmOS website hosted on github. Why not extend and make use of that website? Even editing the website can be done with markdown with Github pages, and you can receive PRs which will grant proper access control, style check tooling etc.

**Comment by ollieparanoid** [comment]
> Right now as you already know different manufacturers have a different take on how much control they should give to their users and different levels of openness regarding publishing their internals. People who want to contribute to the project will be well informed if we guide them through the habits of the manufacturer of various parts and the overall device manufacturer.

That sounds like very useful information. But I'm not sure if we want to stuff all that in the porting guide - how about an extra "Manufacturers" page, that lists such characteristics?

> If everyone if okay with this, I think we should make the porting guide a more detailed version of what is exactly going on with pmbootstrap.

I'm not sure what you mean with *what is exactly going on with pmbootstrap* (example console output?). But nevertheless, please go ahead and improve the guide. **Any edit, that makes it easier for the reader to do the actual porting, is greatly appreciated!**

> 1. [This](https://github.com/postmarketOS/pmbootstrap/wiki/samsung-S7562) page talks how there is a random github repo with the kernel source [..]

I have not found anything on that site with "7562", so it looks like they don't keep the source for old devices on that website. Anyway, I have put the Samsung OSS link [here](https://github.com/postmarketOS/pmbootstrap/wiki/How-to-find-device-specific-information#other-locations-for-kernel-repositories) for now, thanks for that!

But if you found alternative kernel sources or something else to try out, in the case of the device pages, I suggest contacting the contributors mentioned on that page in the [matrix/IRC](https://github.com/postmarketOS/pmbootstrap/wiki/Matrix-and-IRC) channel (which I highly recommend to join for actual porting work, because you can get instant help there) or creating a new issue and tagging the contributor for the device.

> 2. Samsung uses different SoCs [...]

Great information! How about making a new wiki page for GPU drivers, and listing that information there? This would be very useful!

About proprietary drivers: Right now, we only use the open source graphics drivers coming with the kernel, so they render on the CPU as I understand it (please correct me if I'm wrong - my knowledge is thin here), but it's good enough to display phone UIs and even do some (for me at least) impressive weston demos. And they are open source. But having freedreno/lima working at some point would be great of course! (I think the freedreno/lima drivers don't need to be addressed in the porting guide for now - first we'd need to get them working at all, before we could include them in the standard porting process).


> Sidenote: Are there any plans of moving the guides of this repo's wiki? As I see there's a pmOS website hosted on github. Why not extend and make use of that website? Even editing the website can be done with markdown with Github pages, and you can receive PRs which will grant proper access control, style check tooling etc.

I think the entry barrier is a lot lower for editing the wiki, when you do not have to make a PR for each edit. We don't really need more access control, it's working out great so far. But when that should change, we could consider such a move. With that being said, I'd like to have more content on the homepage (mostly announcements), and I've just written it all down in #321 if you're interested.

Everything I've said here is my personal opinion and not necessarily the view of the community. If someone sees it differently, please speak up in this thread.

Thanks for reaching out!

**Comment by PabloCastellano** [comment]
Hey!

Thanks for your comments. I think all of us, collaborators of the project, are fine with having better documentation :)

About the more detailed version of the [Porting Guide](https://github.com/postmarketOS/pmbootstrap/wiki/Porting-to-a-new-device), you say that it expects the reader to know a lot about the **custom ROM ecosystem**. Well, first thing to take into account is that the guide is not focused for everyone but for developers (it would be great to have non-developers porting devices to pmOS though! :smiley:). It is true that you need to have a good background of lots of stuff but I've not found what you mean by the ROM ecosystem (plus I think knowing about Android ROMs would help but it is not a required skill).

About the [Samsung S7562](https://github.com/postmarketOS/pmbootstrap/wiki/samsung-S7562) page, your point definitely makes sense and you are right that it may be confusing. However in this case, I couldn't find anything related to S7562. Also, take into account that only one person seems to have that device, so that none of the other contributors/developers can test it.

You might want to join us on the [Matrix or IRC chat](https://github.com/postmarketOS/pmbootstrap/wiki/Matrix-and-IRC) so that the conversation can be more fluent.

For the rest I subscribe what @ollieparanoid has already said.

**Comment by br0ke** [comment]
@ollieparanoid 

> But I'm not sure if we want to stuff all that in the porting guide - how about an extra "Manufacturers" page, that lists such characteristics?

I think that should work. 

> I'm not sure what you mean with what is exactly going on with pmbootstrap (example console output?).

Sorry, I wasn't clear here. I meant more like how the tool works. In the PC world, you have BIOS, UEFI, etc, and all you need is a drive with the boot sector on for the BIOS to take care of everything from there. But here you seem to need a custom flasher (odin? heimdall?) and other tools just to load the OS onto the phone. More details in this area would give an insight into the architecture of the phones. 

On second thought, I think I'll go ahead and do this. I've just started getting into the Android side of things from Linux/*BSD so all this is new to me. Writing what I learn should help other newbies like me.

> I have not found anything on that site with "7562"

I checked that just now. That was weird on first sight, but looks like there are alternative model numbers for the same device. GT-7568 is another model number for the same device (looks same to me) which does have the kernel source on Samsung's Open Source website.

> How about making a new wiki page for GPU drivers, and listing that information there? 

I'll go ahead and do that. 

> Right now, we only use the open source graphics drivers coming with the kernel, so they render on the CPU as I understand it (please correct me if I'm wrong - my knowledge is thin here), but it's good enough to display phone UIs and even do some (for me at least) impressive weston demos. 

I'm not entirely sure. But I think you're right that we don't really need the GPU for now. 

> I think the freedreno/lima drivers don't need to be addressed in the porting guide for now - first we'd need to get them working at all

That's true.

@PabloCastellano

**Comment by ollieparanoid** [comment]
Awesome, looking forward to your contributions! 👍

**Comment by ollieparanoid** [comment]
I'm closing this, as everything seems to be answered (the tldr version being: just extend the wiki, great that you're doing it!). If you have any more questions or want to talk about this, please answer the ticket.
