### ISSUE TITLE
Repeating motd on some devices in framebuffer console

### ISSUE THREAD

**Issue by antonok-edm** [postmarketOS/pmbootstrap#330]
Enabling CONFIG_FRAMEBUFFER_CONSOLE for asus-grouper results in a repeating motd after unlocking the device. The actual console prompt is inaccessible; text cannot be entered and commands cannot be entered.
Consoles accessed through `ssh` still work as expected.

@PureTryOut also encountered this issue from within a qemu installation.
[Screenshot of the issue on qemu](https://matrix.org/_matrix/media/v1/download/matrix.org/GfPfXVwHJHoCzsZNGclqPyyr)

**Comment by ollieparanoid** [comment]
I assume, that you are running `weston` and that the text appears again after one second, right?
Weston fails to initialize, and that's why the shell session gets restarted, resulting in weston trying to start again. Please try the following:
* Login via SSH and remove [these three lines](https://github.com/postmarketOS/pmbootstrap/blob/e4ffa6264af6ef49fa3b04a217db6a9be1a1ccd2/aports/main/postmarketos-ui-weston/start_weston.sh#L25-L27) from `/etc/profile.d/start_weston.sh` (especially the `exit 1`) - so weston only starts once
* Reboot the device, to make sure we have the first start of weston recorded in the log
* What is in your `/tmp/weston.log`? (you could download it with `scp` from the phone for example)

**Comment by antonok-edm** [comment]
Removing those three lines actually solves it.

Seeing that makes a lot of sense suddenly. I remember enabling the framebuffer console for debugging when weston wasn't working -- of course, now I can see that weston was still attempting to run anyways.

I think it may be more intuitive to just start weston once? I can only imagine someone would kill weston intentionally to restart it manually, or it would crash and probably wouldn't work any better when restarted.

I guess @PureTryOut did mention that he saw the prompt repeat about 20 times before weston started successfully on its own -- although that may be a whole different issue to look into.

**Comment by PureTryOut** [comment]
Note that although Weston did eventually start, it was unusable. I couldn't launch any applications, clicking the terminal icon on the top left didn't launch weston-terminal.

**Comment by ollieparanoid** [comment]
Is this still an issue?

**Comment by PureTryOut** [comment]
Not that I know no.

**Comment by antonok-edm** [comment]
Nope.
