### ISSUE TITLE
Split initramfs causes Sony Z2's networking to break.

### ISSUE THREAD

**Issue by opendata26** [postmarketOS/pmbootstrap#338]
When i connect my device to my computer in the current master nothing happens at all, the splash screen still correctly appears though.

With #257 reverted my device appears in dmesg and i'm able to connect to it with telnet.

**Comment by ollieparanoid** [comment]
First I thought this could have happened, because the system partition was not reflashed. But you have said, that you did that, and your symptoms are different.

According to the code, the boot partition (which is a subpartition of the system image!) gets mounted *after* setting up the networking code, and the networking code is what fails you.

So the only change in the networking code has been in `init_functions.sh`, function `setup_usb_network_android()`:
```diff
-	echo "$(ls /sys/class/udc)" > $CONFIGFS/g1/UDC
+	ls /sys/class/udc > $CONFIGFS/g1/UDC
```
[Location in the full diff](https://github.com/postmarketOS/pmbootstrap/pull/257/files#diff-6513c915087191b94b978efc08f9240eL125)

Could you revert just that single line, and check if it works then?
Thank you very much!

**Comment by opendata26** [comment]
that worked!

**Comment by ollieparanoid** [comment]
Sorry, I did not manage to make a PR for [this diff](https://github.com/postmarketOS/pmbootstrap/issues/338#issuecomment-320502311) today (for which we know it caused a regression). I'll do it soon, but you're welcome to make a PR your self, so it gets fixed faster.

Thanks for your patience in helping to debug and fix this :)
