### ISSUE TITLE
Add toolchain for arm-elf

### ISSUE THREAD

**Issue by MartijnBraam** [postmarketOS/pmbootstrap#399]
I've ran into the first issue for porting pmos to the ipod 1. It doesn't use arm-eabi but arm-elf as its toolchain. My current build output:

```
>>> openiboot: Unpacking /var/cache/distfiles/openiboot.tar.gz...
scons: Reading SConscript files ...
/bin/sh: git: not found
scons: done reading SConscript files.
scons: Building targets ...
arm-elf-gcc -xassembler-with-cpp -mlittle-endian -mfpu=vfp -mthumb -mthumb-interwork -fPIC -nostdlib -Wall -Werror -O2 -Ttext=0x0 -DOPENIBOOT_VERSION=0.3 -DOPENIBOOT_VERSION_BUILD= -DCONFIG_ARM -DARM11 -DCONFIG_S5L8900 "-DOPENIBOOT_VERSION_CONFIG=\" for iPod Touch 1G\"" -DMACH_ID=3558 -DCONFIG_IPOD_TOUCH_1G -Iincludes -Iarch-arm/includes -Iplat-s5l8900/includes -Iacm/includes -Iusb-synopsys/includes -Inor-cfi/includes -Imenu/includes -Imenu -c -o arch-arm/iPodTouch1G_entry.o arch-arm/entry.sx
/bin/sh: arm-elf-gcc: not found
scons: *** [arch-arm/iPodTouch1G_entry.o] Error 127
scons: building terminated because of errors.
```
For testing builds: I've created the `openiboot` package in the `device/ipod1` branch

**Comment by ollieparanoid** [comment]
Looks like you can simply override the toolchain by setting the `CROSS` environment variable (inside `build()`, right before compiling): [ARMEnvironment.SConscript](https://github.com/iDroid-Project/openiBoot/blob/c5cee8cc9e9b13784272550ab0938175cec1cdb5/scons/ARMEnvironment.SConscript#L18-L22)

```shell
	if not env.has_key("CROSS"):
		if env['ENV'].has_key("CROSS"):
			env['CROSS'] = env['ENV']['CROSS']
		else:
			env["CROSS"] = 'arm-elf-'
```

It's so great that you're starting this port! :D

**Comment by ollieparanoid** [comment]
To elaborate a bit more on that, you could:

a) Build it in the native chroot by adding `openiboot` [here](https://github.com/postmarketOS/pmbootstrap/blob/7088c2d2f1f303317583faf5faeb7ac6357b672a/pmb/config/__init__.py#L130) and setting `export CROSS=$CROSS_COMPILE` in `build()` in the APKBUILD, because we set `CROSS` in [pmb.build.package](https://github.com/postmarketOS/pmbootstrap/blob/7088c2d2f1f303317583faf5faeb7ac6357b672a/pmb/build/package.py#L92). I am not sure if this works, but the code above looks like it would.

b) Make sure, that it also builds *without* a cross-compiler in the armhf chroot by patching the lines above out of the sconscript. So it automatically uses the native compiler. (If you implemented a) already, use the `--no-cross` option when compiling)

**Comment by MartijnBraam** [comment]
I've made a patch in pmb in my device/ipod1 branch which makes the openiboot compile in native mode since their build system is fully cross compile aware. Now it's just patching openiboot for gcc6

**Comment by ollieparanoid** [comment]
Really looking forward for getting that working! I'm closing this issue, as the issue about the cross-compiler is solved.
