### ISSUE TITLE
File name too long when caching files

### ISSUE THREAD

**Issue by PabloCastellano** [postmarketOS/pmbootstrap#51]
Hello.

I love your project and would like trying to port Motorola Moto G 2014 (titan).

However the first problem that I found it when running `pmbootstrap.py checksum device-motorola-titan`. 

```
vermuth:~/src/pmbootstrap[master*]$ ./pmbootstrap.py checksum device-motorola-titan
[sudo] password for pablo: 
[12:55:05] Download https://nl.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
[12:55:05] ERROR: [Errno 36] File name too long: '/home/pablo/.local/var/pmbootstrap/cache_http/APKINDEX.tar.gz_87157bd4da30844df6288e4cd88c419f0ec03495207a62a78f88475e61198fcb45f721e421c639a54f6800af86007c0146ef18eeec1febee223ee352a52d28d1'
[12:55:05] Run 'pmbootstrap log' for details.
```

I'm using ecryptfs but not sure if that is the cause. Here is the workaround I did:
https://github.com/PabloCastellano/pmbootstrap/commit/40e5ba651daf0207f45f237eeecb6883c8e8bdb2
Feel free to cherry-pick it

**Comment by ollieparanoid** [comment]
Thanks for all your feedback so far :)

Could you try out the following?
* Change the line to `hashlib.sha256(url.encode("utf-8")).hexdigest())` (256 instead of 512)
* Run `pmbootstrap zap -hc` and clean the http cache, as well as the native chroot
* Run `pmbootstrap chroot` and see if downloading works in that case.

(I'd rather use sha256 instead of a shortened sha512 in the code, if we can - because it looks less like a hack. Cryptographically it [shouldn't matter](https://crypto.stackexchange.com/a/3156), if we used the first 256 bits though.)

**Comment by PabloCastellano** [comment]
Yes, it works! Filename length has gone from 144 chars to 80. 

PR incoming

**Comment by lawl** [comment]
Rel: https://github.com/postmarketOS/pmbootstrap/issues/9
