### ISSUE TITLE
[rx51] real time clock problems 

### ISSUE THREAD

**Issue by pavelmachek** [postmarketOS/pmbootstrap#570]
As soon as you remove battery, RTC loses time. Unfortunately, I remove batteries all the time during development. Wrong time and/or time going backwards does bad stuff to unix system: git clone fails to work due to expired certificates, make fails to rebuild binaries, etc.

I re-built pmOS image, and system booted with date in 1970, even through /etc/passwd had todays date. We can do better.

I'm using this:

#!/bin/bash
F=/etc/zaurus.time
if [ $(date +%s) -lt $(< $F) ];
    then
    date -s @$(< $F)
    fi
date +%s > $F

..runing it during boot and during shutdown. That way, I get approximately right time, good enough for https and make. I see bash might be an issue; if needed, I can rewrite it in sh, C or Python. Would something like this be acceptable?

**Comment by craftyguy** [comment]
This could very simply be a patch to [postmarketos-base.post-install](https://github.com/postmarketOS/pmbootstrap/blob/master/aports/main/postmarketos-base/postmarketos-base.post-install) to just run `rc-update add ntpd default` and then prompt the user during `pmbootstrap init` to select a timezone (which postmarketos-base.post-install can install via symlink to /etc/localtime or use the relevant alpine helper script to do it if there is one)

**Comment by pavelmachek** [comment]
ntpd is nice (and please add it), but will not prevent time going
backwards when network is not available.

make is very unhappy when that happens.

**Comment by craftyguy** [comment]
Just to clarify, the only time that the rtc is reset on board is if battery power is removed, time will not revert to 1970 just because the inet connection is unavailable. 

There's really only one use case I can think of where using ntpd is not going to help, and that's where all of the following events and conditions are true:

- battery has been pulled/replaced

- device booted and inet is unavailable for some reason

- user runs 'make' or does something else (e.g. SSL/TLS) that requires current date/time.

Your implementation would still be a problem if someone shuts off a device for an extended period of time (like a few days/weeks), and then pulled battery/booted w/o inet connection. It would restore an old data/time and still possibly break SSL/TLS (and make `make` complain)

**Comment by pavelmachek** [comment]
No, make would not complain.. because with proposed script, time will
never go backwards.

I have two batteries for N900. When one of them runs empty, I swap
them. So swapping usually happens at some remote place (no WIFI). GPRS
is only started on request...

Yes, ntpd si good idea, but no, it does not solve everything, and
allows time to go backwards.

**Comment by craftyguy** [comment]
I don't understand how your script prevents time from going backwards. Sure, it doesn't go back to 1970, but it does restore the date/time to the date/time when you shut off the device. That can be minutes backward in time, or hours, or days, or weeks (depending on how long it has been since the device was shut off)

**Comment by pavelmachek** [comment]
Ok, so current situation is: date says 190, then 193, then poweroff, battery removed, then date says 2 then 5, poweroff, battery removed, then 4 then 6. RIght? So if you have files with mtime of 3 and 4, you don't know which one is newer, and that's a problem.

With proposed script, date say 190, then 193,  then poweroff, battery removed, then date says 194 then 197, then poweroff, battery removed, then it says 200, then 204. If you have files with mtime 195 and 202, you don't know _when_ they were created, but you know which one is newer.

(So yes, RTC clock in the device do go backward; when operating system is not running. But you can't run "date" without system running, and more importantly you can't create files, so make etc does not get confused).

**Comment by ollieparanoid** [comment]
I think @pavelmachek's workaround is suitable for the problem he (and possibly others in the future) face with development.

@craftyguy: could we agree on, that while this may be only for a specific use case, it **doesn't make the situation worse** and therefore there is no problem implementing it?

**Comment by craftyguy** [comment]
@ollieparanoid yea, after @pavelmachek explained it, it makes more sense now. This is a rx51-specific issue (I will change title back), and I can submit a separate PR for enabling ntpd at boot time, though will need to think about how to handle prompting for timezone.. maybe in `pmbootstrap init`?

**Comment by craftyguy** [comment]
I think the best way to implement this is to:

1) Create a script (modeled after what pavel has here) that the device-nokia-rx51 installs

2) create an init script that is installed in the 'default' and 'shutdown' runlevels by the `device-nokia-rx51.post-install` script, to call the script in (1)

**Comment by ollieparanoid** [comment]
I like the way you would implement it!

A few notes regarding ntpd:
* If we set the hardware clock to UTC/GMT instead of the localtime, we don't need to know the time zone beforehand (it will get calculated based on the UTC time then) ([more info](https://wiki.archlinux.org/index.php/Time#Time_standard))
* Although that might not be obvious, we should take extra care choosing a suitable `ntpd`, *especially* when we want to have it running all the time. After all, it connects to the internet and executes code based on the input it gets, so it has a similar attack surface than curl or wget. Besides busybox' `ntpd`, there is [`openntpd`](http://www.openntpd.org/features.html) from OpenBSD for example, which does proper privilege separation among other features.

**Comment by z3ntu** [comment]
FYI some/many kernels based on sources from CodeAurora (=Qualcomm) disabled the write access to the RTC. See https://forum.fairphone.com/t/fp-open-os-clock-resets-after-reboot/17635/29?u=z3ntu 
Some patch that should solve that is https://github.com/teamgruntled/android_kernel_oppo_find5/commit/df5ab899472f57e98c935719b09023750ffaaaec

**Comment by craftyguy** [comment]
I don't think the problem is writing to it, I think the problem is that the rtc's battery on the n900 is almost always dead now. I could be wrong though.

**Comment by pavelmachek** [comment]
It seems openrc already has support for what I want, see /etc/init.d/swclock .
