### ISSUE TITLE
[nokia-rx51] implement encrypted SWAP

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#574]
I've read through the `fstab` yesterday and noticed, that the N900 has an unencrypted swap.
In my opinion, we should have encrypted swap by default, and if someone has this use case, make it optional to turn it off (maybe along with the `--no-fde` option?)

**Comment by craftyguy** [comment]
Interesting idea, I like it and this should be possible to implement.

One initial concern is that if we use the N900's swap partition for this, then we may break Maemo since it also uses that swap partition. We *could* just ignore the n900's swap partition and use one on the SD card I guess.

**Comment by craftyguy** [comment]
Or, alternatively, we can use a swap file in rootfs. This way, unless a user specifies `--no-fde`, the swap file will automatically be encrypted when the rootfs is encrypted.

This method would be portable to any device running pmos. For the N900, we can just ignore the onboard flash device with it's swap partition and just use a file in rootfs.

**Comment by ollieparanoid** [comment]
I think a swap *file* on the sd-card would be slower than using the existing partition. Maybe someone who has access to maemo could try if the shared partition would work?

According to [that page](https://wiki.gentoo.org/wiki/User:Fearedbliss/Installing_Gentoo_Linux_On_ZFS_Notes#Edit_.2Fetc.2Fconf.d.2Fdmcrypt_.28openrc.29), to encrypt the swap we would write the following to `/etc/conf.d/dmcrypt`:

```
swap=swap
source='/dev/path/to/swap/device'
options='-c aes-xts-plain64 -s 256 -d /dev/urandom'
```

*NOTE: It might make sense to change the cryptsetup options, depending on what 
performs best on the N900 - there's `cryptsetup benchmark`.*


What someone with a N900 with maemo and pmOS running could do:
* in postmarketOS:
  * make sure, that the swap device is *not* listed in /etc/fstab
  * make the changes to `/etc/conf.d/dmcrypt` as written above
  * reboot, check if the encrypted swap device gets used as expected
  * reboot (to maemo)
* in maemo:
  * check if the swap device still gets used automatically

**Comment by craftyguy** [comment]
Why would it be slower? If anything, the SD cards today are much faster (or at least more resilient) than the older built-in flash memory on the N900. 

This method of using a file swap is: 

1) portable to other devices, so we can actually have one set of logic in postmarketos-base that is device-agnostic for setting up swap

2) allows for easy resizing per device or user preference without requiring (re)partitioning

3) encryption comes for free when rootfs is encrypted, so no need to do any other luks-related config

I can try that experiment you mentioned, but I'm almost certain that `swapon` is going to see that the swap partition no longer has a valid swap header (because it got trashed by luks) and fail to enable it in maemo. This is the reason you have to run `mkswap` before you can enable a swap partition/file, and cannot `swapon` any arbitrary file or partition 😄

**Comment by ollieparanoid** [comment]
I would be interested in benchmarks actually. I thought the internal storage might be on a faster bus than the sdcard bus. About the swapon - I assume, that the type=swap is left intact when you configure it as swap device in your mtab. But I could be wrong with both my assumptions here and the swap file solution also sounds good!

Thanks for your insights! 👍

**Comment by craftyguy** [comment]
Good point about type=swap, I don't know what that does.. maybe it just runs 'swapon' after unlocking or something since it's not in fstab anymore?

On the N900, the swap partition is on a "MMC" device, which is also the same device type as the external sd card. 

I can do a benchmark later on to provide some data supporting or destroying my theory. Even if performance is less (as long as it's not significantly less), I think having a unified way to define/handle swap/encrypted swap for all devices would make it a more maintainable OS. Leaving it up to the device maintainers to define how they want to solve this problem for their devices could lead to several implementations when I think only one is necessary to address this issue :)

**Comment by craftyguy** [comment]
Here's some performance data using `dd`. `/dev/mmcblk1p3` is the N900's swap partition, and `/swap` was a file on the rootfs (ext4). No encryption was enabled, but presumably that wouldn't matter if both rootfs and swap were using the same encryption (because why wouldn't they be? :P)

The file writes of 100MB were about 2 seconds faster than the same size writes to the N900's swap partition.

Partition:
```
localhost:/home/user# time dd if=/dev/zero of=/dev/mmcblk1p3 bs=100M count=1
1+0 records out
real    0m 8.60s
user    0m 0.01s
sys     0m 2.68s
localhost:/home/user# time dd if=/dev/zero of=/dev/mmcblk1p3 bs=100M count=1
1+0 records in
1+0 records out
real    0m 8.17s
user    0m 0.01s
sys     0m 2.72s
localhost:/home/user# time dd if=/dev/zero of=/dev/mmcblk1p3 bs=100M count=1
1+0 records in
1+0 records out
real    0m 8.03s
user    0m 0.00s
sys     0m 2.72s

```

File:
```
localhost:/home/user# time dd if=/dev/zero of=/swap bs=100M count=1
1+0 records in
1+0 records out
real    0m 6.10s
user    0m 0.00s
sys     0m 3.13s
localhost:/home/user# time dd if=/dev/zero of=/swap bs=100M count=1
1+0 records in
1+0 records out
real    0m 5.55s
user    0m 0.00s
sys     0m 2.92s
localhost:/home/user# time dd if=/dev/zero of=/swap bs=100M count=1
1+0 records in
1+0 records out
real    0m 6.52s
user    0m 0.00s
sys     0m 3.14s

```

**Comment by ollieparanoid** [comment]
Thanks for making the benchmarks, they really show that writing to a swap file would be faster.
I also like your argument with making it consistent for all devices by using a swap file.
So now I would prefer that solution too 👍

**Comment by craftyguy** [comment]
😄 Ok so I have some more questions for us to discuss regarding how to implement this.

1) When should the file be created, (a) on boot, (b) during `pmbootstrap install`, or (c) some other time?



2) How is swap file size set? Some ideas: (a) during `pmbootstrap init`, (b) in the deviceinfo file for each device, (c) in a new config file `/etc/conf.d/swap_file` (for option 1a above)


For 1a this would result in a smaller image size to flash devices with, but would require creating a new service to make the file if it doesn't exist. 1a would require making a new service to handle creation of the file if it doesn't exist on boot. 1a would work nicely with 2b since the size would be defined in deviceinfo, but maybe having a `/etc/conf.d/swap_file` config is better so it's obvious to users how it could be modified.

For 2a, 1a could be implemented by creating the config file in rootfs to set size and the service would need to be able to reallocate size if the value were to be changed by user. If implementing 1b, then any desired change in size would need to be manually performed by the user (e.g. delete file, fallocate, chmod 600, etc)


As for a default size to use if none is specified/configured, I suggest 768MB, for the only reason that it's the size of the n900's on-device swap partition.

**Comment by ollieparanoid** [comment]
Great write up!

I would prefer `1. a)` (create the file during boot with a service) and a combination of all the options for 2., so let's say `2. d)`:
* The `deviceinfo` file holds a *recommended* swap file size (because for more modern phones you won't need swap at all, and you could make great use of extra 768 MB flash space.)
* You get asked during `pmbootstrap init` how big the swap size should be, and you get the recommended size as default and also displayed as text (so you see it when switching devices and still have the old value)
* That swap size gets written at install time to `/etc/conf.d/swap-file` (there's another file with minus instead of underscore)
