### ISSUE TITLE
[i9300] Unable to use heimdall to flash the pmOS image to my phone

### ISSUE THREAD

**Issue by Asara** [postmarketOS/pmbootstrap#581]
[log.txt](https://github.com/postmarketOS/pmbootstrap/files/1303566/log.txt)
Hey all, attempting to port pmOS to the Samsung Galaxy S3 (i9300).

I am attaching the full output of my pmbootstrap log.txt.  If there is any other info I can provide, I will gladly do so.

Heimdall gets to 8%, regardless of using heimdall directly (after an export) or via pmbootstrap flasher.  

Thanks all!

**Comment by ollieparanoid** [comment]
**Recommended read: https://wiki.postmarketos.org/wiki/Deviceinfo_flash_methods#Odin_mode**

I assume, that you ran into these problems while flashing the system partition?

The Heimdall developers have reverse engineered the proprietary Odin protocol. It is known that it doesn't work perfectly for all devices. You could try to get this resolved upstream by either finding an appropriate, [existing issue](https://github.com/Benjamin-Dobell/Heimdall/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20i9300) or filing a new one (just specify that you're running the latest heimdall and try to flash to the i9300, and the output you get of heimdall). You might need to do the flashing with the proprietary odin and sniff the usb port to actually help with debugging though.

There are a few workarounds though:
* You can install to an sd-card (`pmbootstrap install --sdcard=/dev/mmcblk...`)
* Flash to your device using netcat #456 
* Flash from recovery (e.g. TWRP) if your device has a real boot.img file instead of what we call "isorec (check the wiki article linked above)

... and in case you can't flash the kernel, check out `pmbootstrap export --odin` (you'll need the proprietary odin software for windows though).

So thank you very much for attempting the port and let us know if you need more help!

**Comment by dakk** [comment]
@Asara did you tried methods suggested by @ollieparanoid ? I have the same device and I want to try your port and help you for testing

**Comment by dakk** [comment]
@Asara I got the same problem while flashing partitions to my samsung devices; I fixed with the following steps:

1. Run pmbootstrap flasher, wait for the "<waiting device screen>", then be fast with step 2
2. Put your phone in download mode without the usb cable, then connect the usb cable as fast as possible

After many fails, it worked for me.

**Comment by Asara** [comment]
@dakk Hey thanks for the update.  I haven't had time to give it a go yet, but will try again tonight with @ollieparanoid and your comments.

Was the OS able to boot after that?

**Comment by ollieparanoid** [comment]
Not yet, see #729.

**Comment by ollieparanoid** [comment]
This will be resolved by streamlining `netcat` as flashing method: https://github.com/postmarketOS/pmbootstrap/issues/456#issuecomment-343686341
