### ISSUE TITLE
/var folder in created rootfs is unnecessarily big

### ISSUE THREAD

**Issue by jja2000** [postmarketOS/pmbootstrap#632]
![afbeelding](https://user-images.githubusercontent.com/14004235/30860587-eb7c2c2c-a2c7-11e7-97db-71f71c94c82a.png)

My added packages chosen in pmbootstrap are nano, linux-firmware and alpine-sdk.
Checking the folder shows a ton of cached packages and even the kernel-source:

![afbeelding](https://user-images.githubusercontent.com/14004235/30860651-2ad06866-a2c8-11e7-84c5-2760d195f4a5.png)

And of course linux-firmware being big as usual:

![afbeelding](https://user-images.githubusercontent.com/14004235/30860694-4fa30964-a2c8-11e7-92d6-a7605d7b7881.png)

This only happens when using " ./pmbootstrap install" without any arguments. When installing to a recovery flashable zip the size goes down to 240MB which leads me to believe that doesn't have this problem.

**Comment by MartijnBraam** [comment]
I don't think we need to include the package cache in the generated images. I think the recovery zip generator cleans up way more before creating the .zip file

**Comment by ollieparanoid** [comment]
You mentioned this earlier in the channel, and there I thought the final image would contain the `/var/cache/distfiles` folder (and other caches), which would be a bug.

But now that I look at the screenshots, could it be that you simply ran `ncdu` inside the chroot, not in the extracted image? In that case, having the caches mounted into the chroot is normal behavior.

https://github.com/postmarketOS/pmbootstrap/blob/e60eee7dfa80d2ae07f31c83d1bbb9c56e3d20e4/pmb/config/__init__.py#L94-L106

(You can execute `pmbootstrap shutdown` to umount everything.)

Thanks for creating this detailed issue @jja2000!

**Comment by jja2000** [comment]
@ollieparanoid weird thing is that when I do delete the files through ncdu the rootfs size decreases. I also made sure to pass the --rootfs (can't really remember if it was correct, I did it correctly when I asked jn the channel) argument when chrooting in.

**Comment by ollieparanoid** [comment]
What do you mean with rootfs size, the size of the image?

**Comment by jja2000** [comment]
Yes, the one built after using "./pmbootstrap.py install"

**Comment by ollieparanoid** [comment]
OK thanks for the info, I'll check the code if there is a codepath where it does not umount everything before copying the files, I thought that would not be the case.

**Comment by ollieparanoid** [comment]
The code says, that it always runs `pmb.chroot.shutdown()` (which umounts everything inside the chroot, including the caches), before calling `copy_files_from_chroot()` (which copies the files into the image).

https://github.com/postmarketOS/pmbootstrap/blob/c855ee095b625b981953003f9df5326bbf5a4d39/pmb/install/install.py#L176-L187

Could you try the following?
* Try to reproduce this issue after chroots have been deleted (use `pmbootstrap zap`) and use the `--no-fde` switch for `pmbootstrap install` to disable encryption in order to make it easier to manually mount the image
* After building the bigger image, mount it manually and check if the `/var/cache` folder exists inside it. To mount it, you can use `losetup -f $imagepath`, then you should get two partitions in `/dev/loop0p1` and `/dev/loop0p2` (`p2` is the root partition)

**Comment by drebrez** [comment]
Closing as seems not reproducible anymore. @jja2000 if you still encounter this issue with the latest changes in master branch please reopen it.
