### ISSUE TITLE
Better documentation about the build process

### ISSUE THREAD

**Issue by MartijnBraam** [postmarketOS/pmbootstrap#65]
The [Porting to a new device](https://github.com/postmarketOS/pmbootstrap/wiki/Porting-to-a-new-device) page is now the reference documentation about how pmbootstrap works. 

I think there needs to be another page that describes the whole build process, including what is cached and where, how to invalidate that cache and what component creates the different parts of the image.

That should replace my current build script that nukes everything if something doesn't work:
```bash
DEVICE=lg-hammerhead
RUNNER=./pmbootstrap.py

set -e

yes | $RUNNER zap || echo
yes | $RUNNER zap
$RUNNER checksum device-$DEVICE
$RUNNER build device-$DEVICE --force
$RUNNER checksum linux-$DEVICE
$RUNNER build device-$DEVICE --force
$RUNNER install
```

and now I'm having problems rebuilding my initrd

**Comment by ollieparanoid** [comment]
I have started writing the [build internals](https://github.com/postmarketOS/pmbootstrap/wiki/Build-internals) page.
I think the issue with the initramfs is, that it only gets rebuilt automatically, when the [triggers](https://wiki.alpinelinux.org/wiki/APKBUILD#triggers) get executed.
You could add a call to mkinitfs in your script, something like:
`$RUNNER chroot "mkinitfs --help"`

See also:
https://github.com/postmarketOS/pmbootstrap/blob/master/aports/postmarketos-mkinitfs/postmarketos-mkinitfs.trigger#L15

**Comment by ollieparanoid** [comment]
I'll leave this quote from @MartijnBraam on IRC here as TODO:
> maybe add info about what steps are actually required to rebuild certain parts (like is pmb install required for initrd)

**Comment by ollieparanoid** [comment]
Added a section about the initramfs. Is there anything more you'd like to see documented?

**Comment by ollieparanoid** [comment]
Closing, as discussed on IRC.

**Comment by PabloCastellano** [comment]
Some other topics that might be worth documenting:

- Screen calibration
- Use of prebuilt kernels (extracted from working ROMs, maybe because lack of source code): how to do it, drawbacks and problems
- How to debug a non-working having a working kernel. Finding differences with diffoscope.

**Comment by dzervas** [comment]
It would also be nice to have the final goald of the project (fully open source, firmware free, mainline kernel etc.)
I think it would be convenient to use GH Projects and milestones

-----Original Message-----

**Comment by ollieparanoid** [comment]
Thanks for your input @PabloCastellano and @dzervas!
* New page for [Screen calibration](https://github.com/postmarketOS/pmbootstrap/wiki/Screen-Calibration) added
* Use of prebuilt kernels: I have already written something about that topic in [Troubleshooting](https://github.com/postmarketOS/pmbootstrap/wiki/Troubleshooting) at "Phone shows the Samsung/Google/... splash and nothing else happens!"
* I have added a note now, that diffoscope may be helpful.

Please extend these wiki pages, if you are following them (in your case @PabloCastellano, I think there needs to be something appended to the kernel like a dtb file? But I don't know really much about the Android build process, and I think that they do not use dtb files, right? I think you should be able to find out what is missing when running diffoscope on both kernel images.)

@dzervas: I think a milestone plan is a good idea, but I was kind of confused by github projects, looks like overkill for me for the current project state.
In fact, the mile stones aren't that many right now, and I don't think it makes sense to plan everything until the utopia, that we have reverse engineered firmwares and mainline kernels everywhere.

I am working on a getting the testsuite running with Travis, as you already know. This might take... 2 more weeks or so, but this will vary depending on the other tasks that come in - I prioritize bugs and helping others higher (because we need multiple developers in the long run).

What I will do after that depends on what other people will do with pmbootstrap (but I will work on something :D maybe a new device, maybe fixing drivers, maybe improving other parts of pmbootstrap, if that helps other developers. We'll see.)
And yeah, I can only speak for myself - everyone can work on the parts they are interested in most (be that getting WiFi working, or plasma mobile, or ofono, or whatever).
