### ISSUE TITLE
Can you add chose graphical server in "pmbootstrap init"?

### ISSUE THREAD

**Issue by zhenyolka** [postmarketOS/pmbootstrap#671]
Please, add xorg server in "pmbootstrap init" and configure it. Because on same device screen rotated upside down(with xorg people can rotate screen in config), or non-standart touchscreen driver(it may be configure in xorg.conf). And more graphical enveroiment today on xorg.

**Comment by pavelmachek** [comment]
I started working on xfce4. Currently it is installed, but needs manually copying files from /etc/skel to apply reasonable configuration for a phone.

**Comment by pavelmachek** [comment]
Code is at https://github.com/pavelmachek/pmbootstrap/tree/xfce4-3

**Comment by craftyguy** [comment]
@zhenyolka 

Currently the only options for selection in `pmbootstrap init` are graphical UIs (and currently only weston). I think this selection should be limited to these things (DEs and WMs), since it doesn't make a lot of sense to install, for example, xorg-server but no DE or WM.

If @pavelmachek creates a `postmarketos-ui-xfce4` package, it would get picked up by `init` and displayed as an option, in which case pmbootstrap would install xfce4, xorg, and other dependencies spelled out in his package.

If you really just want to install xorg without any DE or WM, you can do this with `pmbootstrap install --add xorg-server`

**Comment by zhenyolka** [comment]
@pavelmachek in install xfce4 with your repository, but on start i get this(error in file).
[Xorg.0.log](https://github.com/postmarketOS/pmbootstrap/files/1348461/Xorg.0.log)

**Comment by PabloCastellano** [comment]
Since xfce4 ui was merged months ago and the question seems solved I'm closing this issue.

@zhenyolka From your error log, it might be that your device depends on `mesa-dri-swrast` as other devices do already. Don't hesitate to reopen this issue if you consider it necessary.
