### ISSUE TITLE
No boot image generated

### ISSUE THREAD

**Issue by fyfyone** [postmarketOS/pmbootstrap#750]
Hello, I am having noticing issues during `pmbootstrap install`. First of all,
 [this is my Log for both `pmbootstrap build` and `pmboostrap install` from line 4006 onward as well as APKBUILD](https://gist.github.com/fyfyone/c0ee1da32abea1c6f2202b033ec5cfb8).

I think there is no boot image generated because
* of [these](https://gist.github.com/fyfyone/c0ee1da32abea1c6f2202b033ec5cfb8#file-log-txt-L4238-L4247) lines where it says `/boot/dt.img` was not found in `mkbootimg`.
* a generated recovery zip file fails because `boot.img` could not be found.

What can I do to fix this issue and generate `boot/dt.img`?

**Comment by drebrez** [comment]
@fyfyone seems like you mixed some stuff, the `/boot/dt.img` file is necessary if you have to append the DTB to the `boot.img` instead of the kernel.
Should should try to understand where you have to put the DTB for your device, appended to the kernel? or appended to the boot.img?
The `deviceinfo_bootimg_qcdt="true"` variable in the `deviceinfo` file is to append the `/boot/dt.img` to the `boot.img`. 
And from your APKBUILD you are using the kernel with the DTB file appended (`$srcdir/build/arch/arm64/boot/Image.gz-dtb`).
Using the DTB in boot.img you have to generate that `/boot/dt.img` as in [this APKBUILD](https://github.com/postmarketOS/pmbootstrap/blob/0cc7869576dc340a4b42c9789fdef705bc02b92b/aports/device/linux-huawei-y530/APKBUILD#L116)

**Comment by ollieparanoid** [comment]
@fyfyone: are you sure, that you need `deviceinfo_bootimg_qcdt="true"` at all? If you don't know, you probably don't need it and it should work when you remove the line.

**Comment by drebrez** [comment]
@fyfyone I compared the offset you specified in the deviceinfo with those of TWRP and they are different. 
Can you try with the following offests?
```
deviceinfo_flash_offset_base="0x80000000"
deviceinfo_flash_offset_kernel="0x00008000"
deviceinfo_flash_offset_ramdisk="0x02000000"
deviceinfo_flash_offset_second="0x00f00000"
deviceinfo_flash_offset_tags="0x01e00000"
```
edit the `aports/device-huawei-kiwi/deviceinfo` and then the following commands:
`pmbootstrap checksum device-huawei-kiwi`
`pmbootstrap build device-huawei-kiwi --force`
`pmbootstrap initfs build`
`pmbootstrap flasher flash_kernel`

**Comment by fyfyone** [comment]
Thank you! I was now able to flash the kernel which had previously failed with an error. I'm not sure what exactly I changed since I opened this issue, but it was definitely an important step to fix the flash offsets, thank you @drebrez!

Looking back, I should have posted the flash log here for more clues on what's happening.
