### ISSUE TITLE
Add config file for build process

### ISSUE THREAD

**Issue by robinpaulson** [postmarketOS/pmbootstrap#805]
Firstly, apologies if this has been discussed/in progress already, I couldn't find anything similar in the Issues page.

It would be nice to not have to answer all the questions when rebuilding an image, they rarely change. I mean the questions such as "User interface", "Jobs", "Timestamp based rebuilds" and so on.

This could be accomplished by having a "build.config" file, which holds the values for the above questions. If the file is present, running "pmbootstrap init" will run straight through in non-interactive mode. If the file is not present, the user has to answer the questions as per usual, interactively.

So, is there any interest in this? Any suggestions on how to accomplish it; I guess there are python modules which can interact with a .ini or xml file to read the values?

**Comment by ollieparanoid** [comment]
Welcome to postmarketOS!

The idea was, that you only run `pmbootstrap init` when you want to change something in your config, that's why it asks you all the questions. But please tell us more about your use case!

We already save the config in a text file, which is `~/.config/pmbootstrap.cfg`. And you can use `pmbootstrap config` to display/change it directly:
* `pmbootstrap config` lists the whole file
* `pmbootstrap config device` lists the current device
* `pmbootstrap config device lg-mako` changes the current device to lg-mako

**Comment by robinpaulson** [comment]
Hmm, I think I have misunderstood something about how pmb works. I shall close the issue for now and ponder.

Also, thanks for the welcome, it's nice to know new contributors are appreciated. I'm looking forward to pmos moving onwards.
