### ISSUE TITLE
Cant download lineageOS build with wget in chroot

### ISSUE THREAD

**Issue by Qwertie-** [postmarketOS/pmbootstrap#85]
I followed the steps here https://github.com/postmarketOS/pmbootstrap/wiki/How-to-find-device-specific-information

But when I try to wget http://qc4.androidfilehost.com/dl/L0AqIvL2HLf_u_zaY_CkkA/1497416325/817550096634767360/lineage-14.1-20170506-UNOFFICIAL-grouper.zip

it downloads a 36kb file when it should be ~200MB. When I wget outside of chroot it works fine. Is there any way I can copy the file into the chroot from my main system?

**Comment by ollieparanoid** [comment]
* You could try to add `wget` to your `makedepends`, so it uses the "real" wget instead of the BusyBox implementation (the real wget should work exactly the same way as outside of the chroots). See also: *"BusyBox does something different than the standard tool for the job, and this breaks building my package!"* in [Troubleshooting](https://github.com/postmarketOS/pmbootstrap/wiki/Troubleshooting)
* If that does not work, as a workaround, you could copy the file into the "distcache" cache of your chroots (that way it should be like it was already downloaded): `~/.local/var/pmbootstrap/cache_distfiles`

**Comment by ollieparanoid** [comment]
(For the record, it is also possible to define your own `fetch()` method inside the [APKBUILD](https://wiki.alpinelinux.org/wiki/APKBUILD_Reference#fetch.28.29), to have complete control over how it downloads the files. But that shouldn't be necessary here.)

**Comment by Qwertie-** [comment]
I copied the lineageOS zip into ~/.local/var/pmbootstrap/cache_distfiles but I cant see it anywhere in the chroot. Where should it show up?

**Comment by ollieparanoid** [comment]
It should get automatically picked up after your have copied it there, when you have it in your `source=` line in the APKBUILD, because `abuild` (the package building program from Alpine Linux, that `pmbootstrap` wraps around) will use files from there instead of downloading them, when they are present. Inside the chroot, the folder is mounted in `/var/cache/distfiles`.

*(I'd recommend to try to add `wget` to the `makedepends=` line first though.)*
