### ISSUE TITLE
flasher sideload doesn't work

### ISSUE THREAD

**Issue by MoreRobustThanYou** [postmarketOS/pmbootstrap#892]
```./pmbootstrap.py flasher sideload``` returns ```ERROR: Could not find package 'so:libcrypto.so.41' in the aports folder and could not find it in any APKINDEX```

**Comment by ollieparanoid** [comment]
While building the binary repository, I have also seen that. it seems to be related with packages depending on `openssl-dev` and others on `libressl-dev` - `pmbootstrap` doesn't handle it well when one is installed and the other is requested as dependency.

(Alpine packages `libressl` and the `openssl`-packages are a wrapper for them, and there's currently a discussion if they simply name it `libssl` on the mailing list.)

As a workaround, try to zap the folder, and maybe check the dependencies of the programs you're installing. Does it work afterwards? (If so, please don't close this yet, I'd like to get it fixed in pmbootstrap first),

**Comment by ata2001** [comment]
@ollieparanoid It should be fixed after the package gets rebuilt in the alpine repos. 

https://git.alpinelinux.org/cgit/aports/commit/testing/android-tools?id=e38d407f1156c45a0c83d740aef9a2e6d078bc9c

**Comment by MoreRobustThanYou** [comment]
Should be fixed now.
