### ISSUE TITLE
Ability to set max fastboot flash size in deviceinfo

### ISSUE THREAD

**Issue by MoreRobustThanYou** [postmarketOS/pmbootstrap#897]
```amazon-thor``` can't flash files via fastboot that are over 500 MB. I'd like to be able to set the max flash byte size in deviceinfo.

**Comment by MoreRobustThanYou** [comment]
Possibly make a deviceinfo thing called ```flash_fastboot_max_size```, and flasher won't flash anything via fastboot that exceeds said max size

**Comment by ollieparanoid** [comment]
That would increase usability a bit, because then users wouldn't be confronted with a confusing error message from fastboot.

But then again I'd personally rather like to fix the issue with a limited fastboot size altogether than implementing this. Here is the proper fix in my opinion, and it would resolve basically all problems we have with flashing to a system partition and be a good path forward to get LVM across multiple partitions working: https://github.com/postmarketOS/pmbootstrap/issues/456#issuecomment-343686341
