### ISSUE TITLE
Qemu/sdl problems

### ISSUE THREAD

**Issue by robinpaulson** [postmarketOS/pmbootstrap#906]
I updated to the latest pmbootstrap today and tried building for qemu-amd64.

This had worked previously, I perhaps last did it two weeks ago.

This appears to be the problem:
DL1 display code has no opengl support.
Please recompile qemu with SDL2, using
./configure --enable-sdl --with-sdlabi=2.0

I got this with the stock qemu (v2.5) in Ubuntu 16.04. I gather from other issues here that there have been some changes recently in how pmb handles sdl/opengl, etc.

**Comment by PureTryOut** [comment]
Since #861, Qemu now runs with the Virtio drivers to enable 3D hardware acceleration on x86_64. This change required us to launch Qemu with either an SDL or a GTK window. Out of my own tests, the SDL window worked the best and it also had the least amount of dependencies, so we went with it.

To be honest, I expected every major distro to have Qemu compiled with SDL enabled, I guess this is not the case. As a workaround you can choose the `dri-swrast` driver in `./pmbootstrap.py init` for now. It'll remove the SDL dependency, but disable 3D hardware acceleration.

Could you try and see if the GTK interface works for you? You can copy the command `pmbootstrap` uses from `./pmbootstrap.py log` if you run `./pmbootstrap.py qemu`. Replace `-display sdl,gl=on` with `-display gtk,gl=on`. Just run it in a separate terminal.

**Comment by ollieparanoid** [comment]
In fact, you can supply the `display` parameter to `pmbootstrap qemu` now, for example:
```shell
pmbootstrap qemu --display=gk,gl=on
pmbootstrap qemu --display=gk,gl=off
```

Furthermore you can choose the `swrast` mesa driver again, if this still doesn't work for you. `pmbootstrap init` asks which `mesa driver` you want to use.

**Comment by robinpaulson** [comment]
Great, cheers for the suggestions. I'll try specifying the display parameter first and see where that gets me.

As an aside, I'm slightly surprised to see qemu built without a relevant option. I even tried a later version (2.6) from a ppa but got the same errors. I guess I'm only using qemu for testing, so it's not a big problem. As you say, the binaries in Alpine are what's important.

**Comment by robinpaulson** [comment]
Hmm, now this:
qemu-system-x86_64: -display gtk,gl=on: GTK support is disabled
when I run
$ pmbootstrap qemu --image-size=2G --display=gtk,gl=on

**Comment by PureTryOut** [comment]
Yeah so just use the `dri-swrast` driver and don't manually specify a display to use.

**Comment by ollieparanoid** [comment]
The way it works now, it will always pass a `display` parameter to Qemu (no matter which mesa driver you choose). The only exception is SPICE, see below. You can check which values for `display` your `qemu` version supports with: `qemu-system-x86_64 --help | grep display`

```
-h or -help     display this help and exit
-version        display version information and exit
-display sdl[,frame=on|off][,alt_grab=on|off][,ctrl_grab=on|off]
-display gtk[,grab_on_hover=on|off][,gl=on|off]|
-display vnc=<display>[,<optargs>]
-display curses
-display none                select display type
The default display is equivalent to
        "-display gtk"
-curses         shorthand for -display curses
-sdl            shorthand for -display sdl
       [,tls-channel=[main|display|cursor|inputs|record|playback]]
       [,plaintext-channel=[main|display|cursor|inputs|record|playback]]
-vnc <display>  shorthand for -display vnc=<display>
```

"The default display..." text is especially relevant.

If all else fails, we also provide `pmbootstrap qemu --spice`, where the output is done by a SPICE client instead of Qemu. (You'll either need to have `remote-viewer` or `spicy` installed as clients and they get started automatically.)

**Comment by ollieparanoid** [comment]
So this seems to be a problem with the Qemu version of your host system, and not with `pmbootstrap`. In addition nothing happened here since two months, so I'm closing this issue.

Just tell us if you need more support with this issue, then we can reopen it.

**Comment by techgnosis** [comment]
ollieparanoid can you tell us what distro you are using since Ubuntu/Mint doesn't appear to be compiling qemu with SDL or GTK support?

**Comment by ollieparanoid** [comment]
Arch Linux. But the real fix would be having one good version in Alpine, that we can all use. Opened #1158 to track this.
