### ISSUE TITLE
How to compile postmarketOS using prebuilt kernel?

### ISSUE THREAD

**Issue by joshas** [postmarketOS/pmbootstrap#951]
Tried compiling device kernel, but after few patches got stuck on issues in asm code. Because device is using very old kernel (2.6.32.9), I think it might be easier to use prebuilt kernel for now.
I have kernel image, but how to configure postmarketOS build, so it won't compile custom kernel? Are there any example configurations? Wiki info is very vague after kernel extraction.

**Comment by ollieparanoid** [comment]
The [get a patch](https://wiki.postmarketos.org/wiki/Porting_to_a_new_device#Get_a_patch) section of the porting guide should work for ASM code as well.

You won't get very far with the pre-built kernel (ssh will have problems, touch screen in weston will not work, ...). But you can try the following for testing it:
* use `linux-postmarketos` as kernel (because it is in the binary repo) by selecting it as dependency in the `APKBUILD` of your `device-` package
* run `pmbootstrap install` to generate the system image and initramfs
* replace the initramfs from the `boot.img` file of the known working kernel with the initramfs from postmarketOS
* you can get a convenience symlink to the pmOS initramfs with `pmbootstrap export`
