### ISSUE TITLE
Binary repo hinders / confuses

### ISSUE THREAD

**Issue by z3ntu** [postmarketOS/pmbootstrap#985]
I changed something my deviceinfo in aports/device/device-fairphone-fp2/
After that I rebuilt all my local packages (after pmb zap -p) because the changes didn't apply -> didn't help
After `sudo find ~/.local/var/pmbootstrap/ -name "device-fairphone*" -delete` apparently pmbootstrap noticed, that I have a changed version locally and didn't use the version from the repo anymore.
I ran zap multiple times during this process and also rebuilt device-fairphone-fp2 multiple times (`./pmbootstrap.py build device-fairphone-fp2 --arch=armhf --force`)

So apparently the downloaded, cached packages were prioritized over my changed local ones (yes, I didn't bump the pkgrel locally but you shouldn't have to do that, but that would have probably worked)

edit: I hope this comment isn't too confusing the way I wrote it ^^

**Comment by drebrez** [comment]
I think it's the correct behavior if you don't bump the version, why you expect `apk` to get the same version from the repository if he already have it in the cache?
Instead of zapping the packages you can do `zap --distfiles` which cleans the apk cache inside the chroots, this should trigger to cache the new version of the package. But again if it's the same version it doesn't get reinstalled automatically, because there's no reason if it's the same version. but you can force it by calling `apk add -u <path to .apk>`, in the chroot are mounted in `/mnt/pmbootstrap-packages/...`
(ps: I'm not 100% sure about what I wrote, didn't tested it)

**Comment by z3ntu** [comment]
For local development and small changes, I kind of expect pmbootstrap to recognize changed packages (especially because I have `timestamp_based_rebuild = True`)

**Comment by drebrez** [comment]
`timestamp_based_rebuild = True` will trigger the rebuild of the package, but I think what have to be changed is the alpine part of caching the apk inside the system, maybe we can try deleting the cached apk during the rebuild of the package `pmbootstrap chroot -- rm /etc/apk/cache/your_package.apk`

**Comment by ollieparanoid** [comment]
@z3ntu: Thanks for reporting! Let me quote what sums this issue up:

> So apparently the downloaded, cached packages were prioritized over my changed local ones (yes, I didn't bump the pkgrel locally but you shouldn't have to do that, but that would have probably worked)

> I have `timestamp_based_rebuild = True`

Yes, this is a bug and unexpected if you have `timestamp_based_rebuilds` enabled. It should prefer the locally built packages. A few questions:
* Do you know if the package built on the repo had a newer timestamp than the files you've changed locally? I think we don't cover this case yet, and use the files from the repo in that case. But it should be possible to fix it.
* You are not working on any `master` branch, right?

---

@drebrez: thanks for all your input on this, I appreciate it a lot!

> I think it's the correct behavior if you don't bump the version, why you expect `apk` to get the same version from the repository if he already have it in the cache?

Actually we force `apk` to install the locally built version in that case with `pmbootstrap`, whenever `pmb.chroot.apk.install()` is used. So it should have worked.

> Instead of zapping the packages you can do `zap --distfiles` which cleans the apk cache inside the chroots, this should trigger to cache the get new version of the package from the repo.

`pmbootstrap` doesn't scan the downloaded/cached/built binary packages, but only the `APKINDEX.tar.gz` files, which always contain all packages in the repo. So it doesn't make a difference if you clear your `apk` cache, it will only download everything again.

> But again if it's the same version it doesn't get reinstalled automatically, because there's no reason if it's the same version. but you can force it by calling `apk add -u <path to .apk>`, in the chroot are mounted in `/mnt/pmbootstrap-packages/...`

That's just how we force it with `pmb.chroot.apk.install()` 👍

**Comment by ollieparanoid** [comment]
@z3ntu: I thought the issue was, package was not built when there is a binary package of the same version.

So I wrote a test case, and it confirms that an aport with the same version as in the binary repository...
* ... gets rebuilt when the last modified timestamp of the aport is *newer* than the binary package
* ... gets *not* rebuilt when the last modified timestamp of the aport is *older* than the binary package

Whether or not the last point is correct behavior is debatable, but I am not sure if this is related to why you opened the issue in the first place.

So... is this what the issue is about? And if not, could you please provide step by step instructions on how to reproduce your issue, and at which step you would have expected a different result?
